CONSULTAS
1 vista 
INNER JOIN 3
SIMPLE 5
Sub consulta 2

CREATE VIEW Portero as
SELECT E.PAIS, COUNT(J.POSICION) as Porteros
FROM EQUIPO E INNER JOIN JUGADORES J
ON E.ID_EQUIPO = J.ID_EQUIPO
WHERE J.POSICION = 'Portero'
GROUP BY E.PAIS;

SELECT J.NOMBRE, J.PATERNO, J.PAIS_ORIGEN
FROM JUGADORES J INNER JOIN EQUIPO E
ON E.ID_EQUIPO = J.ID_EQUIPO
WHERE J.PAIS_ORIGEN = E.PAIS ;

SELECT E.NOMBRE, COUNT(P.ID_ESTADIO)  FROM ESTADIO E
INNER JOIN PARTIDO P
ON E.ID_ESTADIO = P.ID_ESTADIO
GROUP BY E.NOMBRE
HAVING COUNT(P.ID_ESTADIO) > 3;

SELECT AVG((GOL_L + GOL_V)) as "Promedio Goles" FROM PARTIDO;

SELECT ID_PARTIDO, AVG((GOL_L+GOL_V))  FROM PARTIDO
GROUP BY ID_PARTIDO
HAVING AVG((GOL_L+GOL_V)) > 2;


SELECT SUM(GOL_L) FROM PARTIDO
WHERE ID_LOCAL = '&EQUIPO' ;
SELECT SUM(GOL_V) FROM PARTIDO
WHERE ID_VISITANTE = '&EQUIPO' ;

SELECT COUNT(*) FROM GOL
WHERE TIPO = 'AUTOGOL';

SELECT COUNT(*) FROM FALTAS
WHERE TIPO = 'A';
SELECT COUNT(*) FROM FALTAS
WHERE TIPO = 'R';

SELECT NOMBRE FROM JUGADORES
WHERE ID_JUGADOR = (SELECT ID_JUGADOR FROM ESTADISTICAS WHERE ID_ESTADISTICAS = (SELECT ID_ESTADISTICAS FROM TJUGADO WHERE TIEMPOJUGADO = 0));

SELECT NOMBRE FROM JUGADORES
WHERE ID_JUGADOR IN (SELECT ID_JUGADOR FROM ESTADISTICAS WHERE ID_ESTADISTICAS IN (SELECT ID_ESTADISTICAS FROM TJUGADO WHERE TIEMPOJUGADO BETWEEN 119 and 120))
FETCH FIRST 5 ROWS ONLY;

SELECT E.PAIS, COUNT(FAL.ID_FALTA) as "Numero de faltas" FROM EQUIPO E
INNER JOIN JUGADORES J 
ON J.ID_EQUIPO = E.ID_EQUIPO
INNER JOIN ESTADISTICAS ES ON J.ID_JUGADOR = ES.ID_JUGADOR
INNER JOIN FALTAS FAL ON FAL.ID_ESTADISTICAS = ES.ID_ESTADISTICAS
GROUP BY E.PAIS
ORDER BY COUNT(FAL.ID_FALTA) DESC
FETCH FIRST 1 ROWS ONLY;
