insert into EQUIPO  values (1, 'h', 'Russia');
insert into EQUIPO  values (2, 'f', 'Saudi Arabia');
insert into EQUIPO  values (3, 'b', 'Egypt');
insert into EQUIPO  values (4, 'h', 'Uruguay');
insert into EQUIPO  values (5, 'f', 'Portugal');
insert into EQUIPO  values (6, 'a', 'Spain');
insert into EQUIPO  values (7, 'b', 'Morocco');
insert into EQUIPO  values (8, 'c', 'Iran');
insert into EQUIPO  values (9, 'a', 'France');
insert into EQUIPO  values (10, 'c', 'Australia');
insert into EQUIPO  values (11, 'd', 'Peru');
insert into EQUIPO  values (12, 'a', 'Denmark');
insert into EQUIPO  values (13, 'e', 'Argentina');
insert into EQUIPO  values (14, 'd', 'Iceland');
insert into EQUIPO  values (15, 'b', 'Croatia');
insert into EQUIPO  values (16, 'e', 'Nigeria');
insert into EQUIPO  values (17, 'g', 'Brazil');
insert into EQUIPO  values (18, 'g', 'Switzerland');
insert into EQUIPO  values (19, 'c', 'Costa Rica');
insert into EQUIPO  values (20, 'e', 'Serbia');
insert into EQUIPO  values (21, 'f', 'Germany');
insert into EQUIPO  values (22, 'd', 'Mexico');
insert into EQUIPO  values (23, 'c', 'Sweden');
insert into EQUIPO  values (24, 'h', 'South Korea');
insert into EQUIPO  values (25, 'a', 'Belgium');
insert into EQUIPO  values (26, 'b', 'Panama');
insert into EQUIPO  values (27, 'f', 'Tunisia');
insert into EQUIPO  values (28, 'g', 'England');
insert into EQUIPO  values (29, 'h', 'Poland');
insert into EQUIPO  values (30, 'e', 'Senegal');
insert into EQUIPO  values (31, 'd', 'Colombia');
insert into EQUIPO  values (32, 'g', 'Japan');
