INSERT INTO Personal  values (1001, 9, 8, 8, 'JOSE MAN', 'CAVAZOS', 'DE GYVES', 'M');
INSERT INTO Personal  values (1002, 5, 2, 6, 'ANGEL TOMAS', 'ISIDORO', 'ARANDA', 'M');
INSERT INTO Personal  values (1003, 2, 4, 11, 'JUAN MANUE', 'ALBARADO', 'FELICIANO', 'F');
INSERT INTO Personal  values (1004, 6, 14, 10, 'MIGUEL LUIS', 'PEIRO', 'GORZO', 'F');
INSERT INTO Personal  values (1005, 5, 11, 6, 'MAGDIEL', 'GALEOTE', 'BURRUEL', 'M');
INSERT INTO Personal  values (1006, 5, 15, 2, 'JOSE REFUGIO', 'DEL BOSQUE', 'ELIAS', 'M');
INSERT INTO Personal  values (1007, 8, 6, 6, 'FELIPE ARMANDO', 'LIMA', 'SALANUEVA', 'M');
INSERT INTO Personal  values (1008, 1, 5, 13, 'TOMAS FRANCISCO', 'ARBALLO', 'MULIA', 'M');
INSERT INTO Personal  values (1009, 5, 9, 9, 'DANIEL FELIPE', 'COMPAN', 'BOHORQUEZ', 'M');
INSERT INTO Personal  values (1010, 5, 11, 13, 'JOSE BALTAZAR', 'MALACATE', 'GAMON', 'F');
INSERT INTO Personal  values (1011, 9, 1, 6, 'DAN', 'ZANELLA', 'OCTAVIANO', 'F');
INSERT INTO Personal  values (1012, 2, 6, 13, 'WILLY', 'DE LA', 'TERESA', 'M');
INSERT INTO Personal  values (1013, 10, 11, 9, 'JOSE CONSTANTINO', 'CASTAEDA', 'ARANGURE', 'F');
INSERT INTO Personal  values (1014, 2, 7, 3, 'MIGUEL ANGEL', 'LIEVANA', 'LOBATON', 'M');
INSERT INTO Personal  values (1015, 8, 15, 2, 'ROLDAN', 'SAMANIEGO', 'CIPRIAN', 'M');
INSERT INTO Personal  values (1016, 4, 7, 11, 'MANUEL ALBERTO', 'BURELO', 'NUEZ', 'F');
INSERT INTO Personal  values (1017, 6, 1, 7, 'JOSE LAZARO', 'BATIZ', 'VILLACIS', 'F');
INSERT INTO Personal  values (1018, 1, 15, 8, 'VICTOR SAUL', 'ULIN', 'ZENO', 'M');
INSERT INTO Personal  values (1019, 9, 1, 1, 'PERFECTO', 'AYOMETZI', 'ALAMILLA', 'M');
INSERT INTO Personal  values (1020, 1, 14, 13, 'JOSE ABEL', 'HUCHIM', 'COJ', 'M');
INSERT INTO Personal  values (1021, 9, 6, 11, 'MARIO RAUL', 'CONSUELOS', 'QUEZADAS', 'F');
INSERT INTO Personal  values (1022, 3, 13, 7, 'HUGO ARTURO', 'ALMEJO', 'COLLANTES', 'F');
INSERT INTO Personal  values (1023, 1, 10, 4, 'REY', 'NEJAPA', 'BARRENO', 'M');
INSERT INTO Personal  values (1024, 1, 2, 11, 'CARLOS EFREN', 'SILVIA', 'CABELLO', 'F');
INSERT INTO Personal  values (1025, 3, 10, 5, 'IGNACIO MARTIN', 'MAGA%A', 'ALAFFITA', 'M');
INSERT INTO Personal  values (1026, 8, 12, 4, 'JOSE JACINTO', 'LINOS', 'HUICAB', 'F');
INSERT INTO Personal  values (1027, 5, 3, 9, 'HERVIN', 'BUENO', 'MERINOS', 'F');
INSERT INTO Personal  values (1028, 4, 14, 13, 'IGNACIO ALBERTO', 'NAHUAT', 'TEMORES', 'F');
INSERT INTO Personal  values (1029, 5, 11, 8, 'JOSE ESTEBAN', 'SUSTAITA', 'MINOR', 'M');
INSERT INTO Personal  values (1030, 9, 9, 5, 'JUAN A', 'YOVAL', 'PRIETO', 'F');
INSERT INTO Personal  values (1031, 6, 14, 8, 'CHRISTIAN IVAN', 'BARQUIN', 'CHULIM', 'M');
INSERT INTO Personal  values (1032, 3, 13, 13, 'JOSE DE JE', 'MARTINES', 'IBARES', 'M');
INSERT INTO Personal  values (1033, 9, 14, 9, 'MARTIN RODRIGO', 'DE LA PE!A', 'ZONGUA', 'M');
INSERT INTO Personal  values (1034, 10, 15, 6, 'SERGIO FIDEL', 'ESPINDOLA', 'RUIZ FLORES', 'F');
INSERT INTO Personal  values (1035, 5, 8, 6, 'JAIME RENE', 'RAYAS', 'CASARIN', 'F');
INSERT INTO Personal  values (1036, 7, 2, 7, 'PALEMON', 'GASCA', 'OCAA', 'M');
INSERT INTO Personal  values (1037, 9, 12, 4, 'HUGO ISRAEL', 'BERRA', 'LIZAMA', 'F');
INSERT INTO Personal  values (1038, 8, 3, 12, 'JUAN FRANCIS', 'PERULERO', 'GUIJARRO', 'M');
INSERT INTO Personal  values (1039, 5, 12, 13, 'CAIN', 'CUBILLAS', 'LEANOS', 'M');
INSERT INTO Personal  values (1040, 9, 10, 12, 'SENEN', 'BAMACA', 'PIOQUINTO', 'F');
INSERT INTO Personal  values (1041, 9, 9, 13, 'RICARDO FRANCISCO', 'MENEZ', 'PEDREGUERA', 'M');
INSERT INTO Personal  values (1042, 9, 4, 3, 'PABLO GERARDO', 'CASELIN', 'ESTAOL', 'M');
INSERT INTO Personal  values (1043, 10, 2, 2, 'CARLOS VICENTE', 'ATECPANECATL', 'REYNAGA', 'F');
INSERT INTO Personal  values (1044, 1, 4, 13, 'GUSTAVO ADOLFO', 'CARRISOZA', 'GRANILLO', 'F');
INSERT INTO Personal  values (1045, 9, 2, 11, 'SECUNDINO', 'ADRIAN', 'BALADO', 'M');
INSERT INTO Personal  values (1046, 6, 12, 1, 'MELECIO', 'CHAO', 'KUC', 'M');
INSERT INTO Personal  values (1047, 2, 9, 13, 'SERGIO ANDRES', 'LOBERA', 'XAMAN', 'M');
INSERT INTO Personal  values (1048, 3, 10, 12, 'GIOVANI', 'EPIGMENIO', 'TABASCO', 'M');
INSERT INTO Personal  values (1049, 9, 2, 5, 'JOSE FREDDY', 'CAZADERO', 'CEDANO', 'M');
INSERT INTO Personal  values (1050, 10, 13, 13, 'ADELIN', 'SIGALA', 'GALAN', 'F');
INSERT INTO Personal  values (1051, 3, 6, 7, 'MARTIN ANGEL', 'ESPONDA', 'PALMEROS', 'M');
INSERT INTO Personal  values (1052, 4, 13, 2, 'JOSE HOMERO', 'MERLA', 'CUAUTLE', 'F');
INSERT INTO Personal  values (1053, 4, 13, 6, 'SIMON PEDRO', 'CANTELLANO', 'VICARIO', 'M');
INSERT INTO Personal  values (1054, 4, 7, 8, 'LUIS DAMIAN', 'MORGA', 'PICAZO', 'M');
INSERT INTO Personal  values (1055, 7, 7, 8, 'JOAQUIN DE JESUS', 'LERA', 'ABUNDES', 'M');
INSERT INTO Personal  values (1056, 2, 11, 10, 'CARLOS EUGENIO', 'LAMOYI', 'PAJON', 'F');
INSERT INTO Personal  values (1057, 1, 9, 7, 'ALVARO ANTONIO', 'BALDOVINOS', 'CUERO', 'M');
INSERT INTO Personal  values (1058, 1, 6, 12, 'ARGELIO', 'CASIAN', 'PANIAGUA', 'F');
INSERT INTO Personal  values (1059, 1, 8, 1, 'MARIO CESAR', 'NAVARRETE', 'AZA', 'F');
INSERT INTO Personal  values (1060, 1, 1, 8, 'JESUS JORGE', 'BEAR', 'PERAZA', 'F');
INSERT INTO Personal  values (1061, 6, 1, 10, 'JUAN ISRAEL', 'MADRIGAL', 'ESPARZA', 'F');
INSERT INTO Personal  values (1062, 1, 10, 11, 'ALBERTO ALEJANDRO', 'JANNUZZI', 'ANCONA', 'F');
INSERT INTO Personal  values (1063, 1, 4, 4, 'RAFAEL ARMANDO', 'GIJON', 'GOMORA', 'M');
INSERT INTO Personal  values (1064, 7, 6, 3, 'HERON', 'MARTAGON', 'COUOH', 'F');
INSERT INTO Personal  values (1065, 3, 8, 13, 'JAIME GERARDO', 'GALLEGOS', 'ALCALDE', 'M');
INSERT INTO Personal  values (1066, 9, 6, 7, 'PEDRO FLORENCIO', 'BORJON', 'PERFECTO', 'M');
INSERT INTO Personal  values (1067, 9, 7, 4, 'SACRAMENTO', 'PLANCARTE', 'CANDANEDO', 'F');
INSERT INTO Personal  values (1068, 4, 5, 2, 'MILTON JESUS', 'PODESTA', 'ECHARTEA', 'M');
INSERT INTO Personal  values (1069, 3, 13, 10, 'JESUS ELIAS', 'ZENTELLA', 'TENIZA', 'M');
INSERT INTO Personal  values (1070, 6, 12, 2, 'MARIO LUIS', 'IBA%EZ', 'BARREDO', 'M');
INSERT INTO Personal  values (1071, 4, 2, 1, 'SANTIAGO MANUEL', 'SECA', 'FREGOZO', 'M');
INSERT INTO Personal  values (1072, 4, 2, 7, 'FILIMON', 'MORAN', 'O', 'M');
INSERT INTO Personal  values (1073, 5, 14, 8, 'JAVIER IGNACIO', 'ALEJOS', 'SANZ', 'M');
INSERT INTO Personal  values (1074, 7, 7, 4, 'ALEXANDER', 'BA!UELOS', 'OLETA', 'F');
INSERT INTO Personal  values (1075, 1, 10, 13, 'RICARDO MIGUEL', 'ENSALDO', 'DE LA HUERTA', 'F');
INSERT INTO Personal  values (1076, 4, 1, 12, 'CASTO', 'NOGUEDA', 'HUESO', 'M');
INSERT INTO Personal  values (1077, 6, 3, 13, 'PABLO HUMBERTO', 'AMABLE', 'OVANDO', 'M');
INSERT INTO Personal  values (1078, 4, 1, 13, 'CRESENCIANO', 'FILEMON', 'VIDAURI', 'F');
INSERT INTO Personal  values (1079, 5, 9, 2, 'TEOFILO', 'LLERGO', 'TIPACAMU', 'F');
INSERT INTO Personal  values (1080, 9, 13, 1, 'MIGUEL AGUSTIN', 'MURATALLA', 'SANTAELLA', 'M');
INSERT INTO Personal  values (1081, 1, 8, 11, 'ERMELANDO', 'ACA', 'MOJARRAS', 'F');
INSERT INTO Personal  values (1082, 5, 6, 7, 'HECTOR M', 'BATUN', 'GIRON', 'F');
INSERT INTO Personal  values (1083, 6, 5, 9, 'GUSTAVO ARMANDO', 'CHALMA', 'ACO', 'M');
INSERT INTO Personal  values (1084, 6, 15, 8, 'EDGAR SALVADOR', 'ARRONTE', 'ARISTA', 'F');
INSERT INTO Personal  values (1085, 8, 5, 8, 'JOSE ISMAEL', 'CUBILLOS', 'MENDOZA', 'M');
INSERT INTO Personal  values (1086, 3, 15, 2, 'NARCIZO', 'MARCHAND', 'PIZA', 'F');
INSERT INTO Personal  values (1087, 5, 6, 9, 'JABIER', 'MICHEL', 'CHAC', 'M');
INSERT INTO Personal  values (1088, 6, 3, 8, 'JESUS ARNULFO', 'ORDOϿEZ', 'VILLALBAZO', 'M');
INSERT INTO Personal  values (1089, 6, 6, 8, 'GUSTAVO ERNESTO', 'SALVA', 'VIRGEN', 'M');
INSERT INTO Personal  values (1090, 3, 11, 9, 'TIRSO', 'ORBE', 'ANGELITO', 'F');
INSERT INTO Personal  values (1091, 3, 6, 9, 'ANTONIA', 'NEY', 'OAXACA', 'F');
INSERT INTO Personal  values (1092, 7, 9, 4, 'WILLIAN', 'REGUEIRA', 'BARROSA', 'F');
INSERT INTO Personal  values (1093, 7, 9, 13, 'PAVEL', 'GUICHO', 'HOY', 'M');
INSERT INTO Personal  values (1094, 2, 12, 8, 'FABRICIO', 'ISABELES', 'AVILEZ', 'M');
INSERT INTO Personal  values (1095, 5, 12, 9, 'CARLOS EDUARDO', 'CITLAHUA', 'LISEA', 'M');
INSERT INTO Personal  values (1096, 7, 4, 11, 'EYMARD', 'PAULA', 'PAVIAN', 'F');
INSERT INTO Personal  values (1097, 2, 15, 12, 'NEIL', 'NOCHEBUENA', 'CANTELLANO', 'F');
INSERT INTO Personal  values (1098, 10, 9, 1, 'EDGAR ULISES', 'CIH', 'RAYMUNDO', 'F');
INSERT INTO Personal  values (1099, 6, 11, 12, 'EDMUNDO GERARDO', 'COX', 'PINETE', 'F');
INSERT INTO Personal  values (1100, 5, 9, 8, 'DANIEL ARTURO', 'CATANA', 'TAJONAR', 'F');
INSERT INTO Personal  values (1101, 4, 1, 5, 'ANTONIO ESTEBAN', 'RIBOTA', 'NAREDO', 'M');
INSERT INTO Personal  values (1102, 9, 5, 13, 'JESUS ISIDRO', 'IBARRIA', 'TRONCO', 'M');
INSERT INTO Personal  values (1103, 9, 13, 8, 'RAFAEL ALFONSO', 'CRUZALEY', 'FRAIRE', 'F');
INSERT INTO Personal  values (1104, 2, 5, 5, 'JORGE JAVIER', 'ASTIVIA', 'GARZA', 'F');
INSERT INTO Personal  values (1105, 6, 3, 8, 'VITO', 'VILLAURRUTIA', 'HUIPE', 'M');
INSERT INTO Personal  values (1106, 4, 2, 7, 'EDGAR VLADIMIR', 'BANDA', 'CALATA', 'F');
INSERT INTO Personal  values (1107, 6, 5, 6, 'DAVID RAFAEL', 'CARMEN', 'AYOHUA', 'F');
INSERT INTO Personal  values (1108, 5, 11, 7, 'CHRISTIAN ISRAEL', 'ZANABRIA', 'HIRALES', 'M');
INSERT INTO Personal  values (1109, 7, 7, 6, 'FRANCISCO TOMAS', 'CASTELL', 'TRILLO', 'M');
INSERT INTO Personal  values (1110, 4, 1, 7, 'AUSENCIO', 'EZQUEDA', 'ARREGUIN', 'M');
INSERT INTO Personal  values (1111, 2, 14, 11, 'FRANCISCO BERNARDO', 'ZOTEA', 'CHEPETLA', 'M');
INSERT INTO Personal  values (1112, 8, 13, 10, 'RUBEN GERARDO', 'CHORA', 'LABANA', 'F');
INSERT INTO Personal  values (1113, 3, 6, 2, 'HECTOR FERNANDO', 'DIMAYUGA', 'VENANCIO', 'M');
INSERT INTO Personal  values (1114, 7, 1, 1, 'BENIGNO', 'ANDABLO', 'CARREO', 'F');
INSERT INTO Personal  values (1115, 7, 2, 13, 'FRANCISCO OMAR', 'LIMETA', 'VERDINES', 'M');
INSERT INTO Personal  values (1116, 1, 10, 12, 'ROBERTO JAIME', 'MENDIZABAL', 'GAMA', 'F');
INSERT INTO Personal  values (1117, 4, 9, 11, 'JOSE FABIAN', 'ALBANIL', 'ROSSELL', 'F');
INSERT INTO Personal  values (1118, 2, 7, 4, 'SINHUE', 'OLACHEA', 'TENREIRO', 'M');
INSERT INTO Personal  values (1119, 4, 7, 3, 'LIMBERG', 'AIVAR', 'MASTRANZO', 'F');
INSERT INTO Personal  values (1120, 1, 14, 8, 'VERULO', 'YANEZ', 'BERRIOZABAL', 'F');
INSERT INTO Personal  values (1121, 9, 1, 3, 'PATRICIA', 'LANGARICA', 'PEUELAS', 'F');
INSERT INTO Personal  values (1122, 7, 4, 8, 'PRICILIANO', 'PINTOS', 'CANCINO', 'F');
INSERT INTO Personal  values (1123, 3, 2, 5, 'MARTIN RENE', 'SABAS', 'REDONA', 'M');
INSERT INTO Personal  values (1124, 5, 15, 10, 'RAMON FERNANDO', 'PESQUERA', 'ESCAPITA', 'M');
INSERT INTO Personal  values (1125, 7, 3, 7, 'RICARDO JAVIER', 'BAILEY', 'MENDIOZA', 'M');
INSERT INTO Personal  values (1126, 7, 14, 2, 'HAMLET', 'CALLEJO', 'LLANITO', 'F');
INSERT INTO Personal  values (1127, 10, 6, 9, 'RAFAEL FRANCISCO', 'BIVIAN', 'OJENDIS', 'F');
INSERT INTO Personal  values (1128, 9, 9, 9, 'ALVARO JAVIER', 'COL', 'COL', 'M');
INSERT INTO Personal  values (1129, 1, 15, 8, 'NOE JAVIER', 'ALMERAZ', 'MANTILLA', 'F');
INSERT INTO Personal  values (1130, 8, 8, 11, 'DAVID ARTURO', 'SOLLANO', 'ESCUTIA', 'F');
INSERT INTO Personal  values (1131, 9, 14, 4, 'FCO JAVIER', 'PICON', 'PASION', 'M');
INSERT INTO Personal  values (1132, 1, 6, 4, 'JOSE JOSE', 'LLERA', 'MONJARAS', 'F');
INSERT INTO Personal  values (1133, 8, 10, 7, 'RAUL GERARDO', 'TEJEDOR', 'VIZAR', 'F');
INSERT INTO Personal  values (1134, 3, 15, 11, 'J IGNACIO', 'TESILLOS', 'ALMAZO', 'F');
INSERT INTO Personal  values (1135, 9, 7, 3, 'OSCAR SALVADOR', 'PERETE', 'BOSQUES', 'F');
INSERT INTO Personal  values (1136, 1, 7, 12, 'EDGAR OSWALDO', 'GALDEANO', 'ATENCIO', 'M');
INSERT INTO Personal  values (1137, 6, 8, 10, 'DELMAR', 'VIZARRETEA', 'PAREDES', 'M');
INSERT INTO Personal  values (1138, 5, 14, 7, 'JOSE IGNACIO', 'MARANON', 'PASAFLORES', 'M');
INSERT INTO Personal  values (1139, 8, 4, 6, 'JORAM', 'LINDERO', 'BAROCIO', 'M');
INSERT INTO Personal  values (1140, 4, 8, 4, 'ENRIQUE ALONSO', 'NANGO', 'BAINORI', 'M');
INSERT INTO Personal  values (1141, 1, 8, 11, 'JORGE GILBERTO', 'CAPUCHINO', 'FILEMON', 'M');
INSERT INTO Personal  values (1142, 5, 10, 9, 'MARTIN ALFREDO', 'MA', 'CAPETILLO', 'M');
INSERT INTO Personal  values (1143, 9, 10, 12, 'QUINTIL', 'PADRENAN', 'OCADIZ', 'F');
INSERT INTO Personal  values (1144, 9, 5, 11, 'HECTOR MANU', 'LEGARRETA', 'MATEO', 'M');
INSERT INTO Personal  values (1145, 6, 7, 8, 'MANUEL ABRAHAM', 'RUGERIO', 'SAMPERIO', 'F');
INSERT INTO Personal  values (1146, 2, 12, 2, 'JOSE MERCEDES', 'RICHART', 'TEPOZTECO', 'M');
INSERT INTO Personal  values (1147, 7, 8, 13, 'JAVIER NICOLAS', 'CHONA', 'CUNDAPI', 'M');
INSERT INTO Personal  values (1148, 2, 4, 12, 'JOSE SIXTO', 'REATIGA', 'MARQUEZ', 'F');
INSERT INTO Personal  values (1149, 8, 12, 2, 'DANIEL ANGEL', 'CARCA!O', 'AGUEDA', 'F');
INSERT INTO Personal  values (1150, 6, 7, 13, 'FERNANDO GUADALUPE', 'MOTTU', 'MORTEO', 'F');
INSERT INTO Personal  values (1151, 7, 8, 11, 'CESAR MIGUEL', 'JIMENEZ', 'PACHUCA', 'F');
INSERT INTO Personal  values (1152, 1, 6, 5, 'HECTOR JAVIER', 'MATU', 'CATARINO', 'M');
INSERT INTO Personal  values (1153, 4, 7, 3, 'GUSTAVO SALVADOR', 'LOYA', 'ESQUIVIAS', 'M');
INSERT INTO Personal  values (1154, 6, 7, 4, 'ANGELBERTO', 'SIXTO', 'ABUD', 'M');
INSERT INTO Personal  values (1155, 9, 11, 7, 'DANIEL ROBERTO', 'OCEGUEDA', 'SAGASTUME', 'M');
INSERT INTO Personal  values (1156, 4, 7, 11, 'PABLO', 'PEIMBERT', 'GINEZ', 'M');
INSERT INTO Personal  values (1157, 7, 11, 12, 'EPIFANIO', 'MONTES', 'GARDU!O', 'F');
INSERT INTO Personal  values (1158, 8, 13, 1, 'FERMIN', 'CANCHOLA', 'GALLOSO', 'F');
INSERT INTO Personal  values (1159, 4, 11, 12, 'JORGE ALBE', 'ALDECUA', 'SUARES', 'F');
INSERT INTO Personal  values (1160, 5, 6, 5, 'JULIO ERNESTO', 'CHEW', 'NU%O', 'M');
INSERT INTO Personal  values (1161, 7, 8, 9, 'CRISTO', 'CHONG', 'MAGAÿA', 'M');
INSERT INTO Personal  values (1162, 5, 1, 6, 'WILMER', 'VIZCARRA', 'PERZABAL', 'F');
INSERT INTO Personal  values (1163, 2, 2, 3, 'PEDRO ARTURO', 'JULIAN', 'MAGNO', 'M');
INSERT INTO Personal  values (1164, 5, 2, 5, 'GAUDENCIO', 'EVARISTO', 'LABORIN', 'M');
INSERT INTO Personal  values (1165, 10, 13, 11, 'ANTONIO ENRIQUE', 'CASTELAZO', 'ORONA', 'M');
INSERT INTO Personal  values (1166, 6, 13, 11, 'ISAIN', 'HERAZO', 'ASTUDILLO', 'F');
INSERT INTO Personal  values (1167, 7, 5, 8, 'ATENOGENES', 'VELEZ', 'ALVIZAR', 'F');
INSERT INTO Personal  values (1168, 7, 8, 7, 'AVERTANO', 'CIPRIANO', 'TOMAS', 'M');
INSERT INTO Personal  values (1169, 4, 11, 3, 'OMAR RICARDO', 'SUMUANO', 'ZERMENO', 'F');
INSERT INTO Personal  values (1170, 3, 13, 9, 'RUTILO', 'ARZATE', 'MAZA', 'M');
INSERT INTO Personal  values (1171, 5, 1, 8, 'FELIPE MIGUEL', 'PANDO', 'ANCHEITA', 'F');
INSERT INTO Personal  values (1172, 10, 13, 3, 'NEMECIO', 'FUNES', 'GRANO', 'M');
INSERT INTO Personal  values (1173, 5, 7, 10, 'CARLOS RAMON', 'ALDANA', 'ROSIQUE', 'M');
INSERT INTO Personal  values (1174, 5, 1, 10, 'HECTOR TOMAS', 'NARCIZO', 'DOUGLAS', 'F');
INSERT INTO Personal  values (1175, 6, 3, 3, 'JESUS OCTAVIO', 'BAINORI', 'PERAFAN', 'M');
INSERT INTO Personal  values (1176, 7, 15, 12, 'FRANCISCO HERIBERTO', 'JAYME', 'PEREDO', 'M');
INSERT INTO Personal  values (1177, 5, 15, 8, 'JORGE ANGEL', 'CHAVERRI', 'RIEKE', 'M');
INSERT INTO Personal  values (1178, 5, 4, 4, 'JOSE SERAFIN', 'BUJANDA', 'ARRAZATE', 'M');
INSERT INTO Personal  values (1179, 6, 14, 7, 'JOSE FIDEL', 'GODINA', 'NURICUMBO', 'M');
INSERT INTO Personal  values (1180, 10, 10, 7, 'JULIO DANIEL', 'SANTIBANEZ', 'VIZCAINO', 'F');
INSERT INTO Personal  values (1181, 8, 6, 4, 'JORGE VICENTE', 'HUERFANO', 'WILCHIS', 'M');
INSERT INTO Personal  values (1182, 4, 1, 1, 'BERZAIN', 'CARDENA', 'ZINK', 'M');
INSERT INTO Personal  values (1183, 3, 4, 9, 'CARLOS ALBERT', 'SMER', 'AYOMETZI', 'F');
INSERT INTO Personal  values (1184, 2, 14, 6, 'SABAS', 'RODEA', 'PETRIZ', 'F');
INSERT INTO Personal  values (1185, 2, 11, 6, 'VICTOR HUG', 'CASTREJON', 'PEVIA', 'F');
INSERT INTO Personal  values (1186, 8, 6, 7, 'VILIULFO', 'PANDURO', 'ESCARRAGA', 'F');
INSERT INTO Personal  values (1187, 2, 15, 12, 'NATALIO', 'CARACAS', 'ARCINIEGA', 'M');
INSERT INTO Personal  values (1188, 6, 14, 2, 'ANDREI', 'MOO', 'TERRIQUEZ', 'F');
INSERT INTO Personal  values (1189, 3, 12, 12, 'VICTOR LUIS', 'LAVEAGA', 'MONGE', 'M');
INSERT INTO Personal  values (1190, 10, 14, 2, 'HERBEY', 'SEGOVIA', 'LASTRA', 'F');
INSERT INTO Personal  values (1191, 7, 6, 10, 'DAVID ARMANDO', 'CUAMANI', 'GRANDA', 'M');
INSERT INTO Personal  values (1192, 6, 4, 13, 'VICTOR RAUL', 'RODELO', 'TEQUIDA', 'M');
INSERT INTO Personal  values (1193, 8, 7, 6, 'LUCIO', 'NUCAMENDI', 'DARIO', 'M');
INSERT INTO Personal  values (1194, 4, 9, 6, 'JORGE SAUL', 'PASCUALENO', 'ALMERAYA', 'F');
INSERT INTO Personal  values (1195, 6, 10, 7, 'ESTUARDO', 'AMBROS', 'ZAVALZA', 'M');
INSERT INTO Personal  values (1196, 2, 4, 13, 'FELIX ARMANDO', 'YOLIMEA', 'SEBOA', 'M');
INSERT INTO Personal  values (1197, 10, 7, 6, 'FRANCISCO MANUEL', 'TRANCOSO', 'CAADA', 'F');
INSERT INTO Personal  values (1198, 4, 1, 8, 'SIXTO', 'CARDEL', 'TIZNADO', 'M');
INSERT INTO Personal  values (1199, 8, 2, 2, 'LUIS JORGE', 'ALEXANDER', 'BELMAN', 'F');
INSERT INTO Personal  values (1200, 8, 2, 5, 'LEOVIGILDO', 'CARDONA', 'COMPEAN', 'M');
INSERT INTO Personal  values (1201, 1, 3, 3, 'CUDBERTO', 'DAZA', 'ADRIAN', 'F');
INSERT INTO Personal  values (1202, 2, 13, 7, 'ARMANDO JESUS', 'VILLELA', 'CABRAL', 'M');
INSERT INTO Personal  values (1203, 1, 14, 10, 'PIO', 'RETANA', 'NACAR', 'M');
INSERT INTO Personal  values (1204, 3, 5, 7, 'LUIS JAIME', 'CONSUELO', 'CALVARIO', 'M');
INSERT INTO Personal  values (1205, 6, 15, 11, 'JESUS JOSE', 'FLORENTINO', 'RUTIAGA', 'F');
INSERT INTO Personal  values (1206, 4, 13, 2, 'PEDRO FRANCISCO', 'BENCOMO', 'ALMENDAREZ', 'M');
INSERT INTO Personal  values (1207, 6, 9, 12, 'FERNANDO ALFONSO', 'OLVEDA', 'SANAGUSTIN', 'M');
INSERT INTO Personal  values (1208, 4, 4, 5, 'SEIN', 'MIRALRIO', 'CUMPLIDO', 'M');
INSERT INTO Personal  values (1209, 1, 12, 8, 'JUAN JAVIER', 'SIAS', 'GUICHARD', 'F');
INSERT INTO Personal  values (1210, 9, 8, 5, 'JUAN ROGELIO', 'ZINK', 'TEJERO', 'M');
INSERT INTO Personal  values (1211, 4, 4, 5, 'BELISARIO', 'LAYNA', 'VIRRUETA', 'F');
INSERT INTO Personal  values (1212, 6, 11, 8, 'RAMON OMAR', 'CIMENTAL', 'RIVEROL', 'F');
INSERT INTO Personal  values (1213, 10, 4, 5, 'ANGEL ARTURO', 'NETZAHUAL', 'DALMAN', 'F');
INSERT INTO Personal  values (1214, 9, 8, 1, 'LIZANDRO', 'FONG', 'INURRETA', 'F');
INSERT INTO Personal  values (1215, 8, 12, 9, 'AGUSTIN GERARDO', 'PELCASTRE', 'BENCOMO', 'M');
INSERT INTO Personal  values (1216, 9, 6, 7, 'CELEDONIO', 'CANEDO', 'BUSTILLOS', 'M');
INSERT INTO Personal  values (1217, 8, 10, 3, 'RAMIRO DE JESUS', 'LUVIAN', 'UGUES', 'M');
INSERT INTO Personal  values (1218, 7, 12, 4, 'HERMELINDO', 'NORMAN', 'IZUCAR', 'F');
INSERT INTO Personal  values (1219, 2, 14, 9, 'PABLO OMAR', 'FIGUEIRAS', 'DE LEON', 'F');
INSERT INTO Personal  values (1220, 4, 9, 2, 'CARLOS MOISES', 'MAZCORRO', 'ARREDONDO', 'F');
INSERT INTO Personal  values (1221, 7, 13, 4, 'FRANCISCO FIDEL', 'CARBAJAL', 'BONIFACIO', 'M');
INSERT INTO Personal  values (1222, 1, 3, 4, 'MIGUEL ALFREDO', 'ROCHER', 'BRISTOL', 'F');
INSERT INTO Personal  values (1223, 5, 2, 8, 'RAMON ARTURO', 'RILEY', 'FLORIDO', 'F');
INSERT INTO Personal  values (1224, 3, 2, 7, 'RUFO', 'MU%IZ', 'BAYLON', 'M');
INSERT INTO Personal  values (1225, 7, 12, 13, 'JARED', 'TOXTLE', 'SEDANO', 'F');
INSERT INTO Personal  values (1226, 5, 12, 8, 'JOSE INES', 'BARTOLO', 'LOPEZ DE LARA', 'M');
INSERT INTO Personal  values (1227, 3, 4, 2, 'MELCHISEDEC', 'MERCADO', 'TAMARINDO', 'F');
INSERT INTO Personal  values (1228, 9, 9, 5, 'ANIBAL', 'LEGASPE', 'CRISTALINAS', 'F');
INSERT INTO Personal  values (1229, 1, 12, 5, 'RICARDO IVAN', 'COLUNGA', 'ESCOBEDO', 'M');
INSERT INTO Personal  values (1230, 2, 12, 13, 'LUIS ERNESTO', 'CAJUN', 'RIBERA', 'F');
INSERT INTO Personal  values (1231, 6, 7, 4, 'EVERALDO', 'CASERES', 'VICTORIO', 'M');
INSERT INTO Personal  values (1232, 5, 6, 9, 'DAVID JESUS', 'PUNTOS', 'ALTAMIRANO', 'M');
INSERT INTO Personal  values (1233, 7, 6, 6, 'JOSE ALFONSO', 'TORRUCO', 'GAMIO', 'M');
INSERT INTO Personal  values (1234, 5, 10, 10, 'LUIS RAMON', 'LEZA', 'DE LOS ANGELES', 'M');
INSERT INTO Personal  values (1235, 5, 11, 8, 'JERONIMO', 'ARZAGA', 'GASPARILLO', 'F');
INSERT INTO Personal  values (1236, 10, 7, 1, 'HUBER', 'ZAZUETA', 'SEGURA', 'F');
INSERT INTO Personal  values (1237, 2, 12, 4, 'HECTOR ESTEBAN', 'GALBRAITH', 'VILLADOBLE', 'M');
INSERT INTO Personal  values (1238, 1, 1, 4, 'EDUARDO RENE', 'BALDENEBRO', 'MADRID', 'M');
INSERT INTO Personal  values (1239, 3, 5, 10, 'QUINTIN', 'TZAKUM', 'TEPEYAC', 'M');
INSERT INTO Personal  values (1240, 10, 10, 7, 'VULFRANO', 'MONDACA', 'GONZLEZ', 'F');
INSERT INTO Personal  values (1241, 2, 7, 12, 'FEDERICO', 'ABITIA', 'PAUL', 'F');
INSERT INTO Personal  values (1242, 5, 14, 5, 'JUAN MARIA', 'LIMONES', 'QUIRALTE', 'M');
INSERT INTO Personal  values (1243, 1, 4, 3, 'MISAEL', 'PENICHE', 'ALAMIRRA', 'F');
INSERT INTO Personal  values (1244, 4, 12, 9, 'JOSE GENARO', 'ORROSTIETA', 'CONTRERAS', 'M');
INSERT INTO Personal  values (1245, 5, 5, 9, 'ELESBAN', 'CUTIO', 'NOTARIO', 'M');
INSERT INTO Personal  values (1246, 6, 8, 11, 'MARIO CARLOS', 'PEA', 'ESPERON', 'F');
INSERT INTO Personal  values (1247, 6, 7, 8, 'EDU', 'ORIGEL', 'MANI', 'F');
INSERT INTO Personal  values (1248, 2, 7, 6, 'MANUEL DE JESUS', 'YEN', 'DITTRICH', 'M');
INSERT INTO Personal  values (1249, 8, 5, 8, 'INOCENCIO', 'BIXANO', 'AMAVISCA', 'M');
INSERT INTO Personal  values (1250, 1, 3, 4, 'GERARDO ISRAEL', 'DE JULIAN', 'MURIEL', 'F');
INSERT INTO Personal  values (1251, 8, 12, 8, 'GERARDO ALFONSO', 'MAYORA', 'LLERENAS', 'M');
INSERT INTO Personal  values (1252, 8, 1, 9, 'HERMENEGILDO', 'FAVELA', 'EUGENIA', 'F');
INSERT INTO Personal  values (1253, 6, 8, 7, 'IVAN OMAR', 'GOROSTIETA', 'MOZQUEDA', 'F');
INSERT INTO Personal  values (1254, 9, 15, 1, 'ATAULFO', 'CHICMUL', 'TACU', 'M');
INSERT INTO Personal  values (1255, 7, 1, 7, 'JUAN IGNACIO', 'ACU%A', 'JUSTO', 'M');
INSERT INTO Personal  values (1256, 10, 12, 5, 'ERICK OMAR', 'BACASEHUA', 'SORIA', 'M');
INSERT INTO Personal  values (1257, 7, 12, 8, 'MARIO HECTOR', 'GACHUPIN', 'CANEL', 'M');
INSERT INTO Personal  values (1258, 9, 8, 10, 'DAVID ALEJANDRO', 'ESPANA', 'CORROY', 'M');
INSERT INTO Personal  values (1259, 3, 6, 2, 'PEDRO DAVID', 'PEREIDA', 'CATALAN', 'F');
INSERT INTO Personal  values (1260, 6, 7, 1, 'ARTURO EMMANUEL', 'CAICEROS', 'URIETA', 'M');
INSERT INTO Personal  values (1261, 7, 2, 9, 'ABRAHAM DE JESUS', 'MAZA', 'FIESCO', 'F');
INSERT INTO Personal  values (1262, 5, 2, 1, 'OMAR ARTURO', 'FIESCO', 'ALARCON', 'M');
INSERT INTO Personal  values (1263, 10, 2, 9, 'ALDO OMAR', 'WILLIAMS', 'GAVILANES', 'M');
INSERT INTO Personal  values (1264, 2, 7, 3, 'NOE', 'AZARCOYA', 'NAEZ', 'M');
INSERT INTO Personal  values (1265, 4, 3, 2, 'EMIDIO', 'MATURINO', 'MASSE', 'M');
INSERT INTO Personal  values (1266, 10, 14, 8, 'JOSE ANDRES', 'COB', 'SIMBRON', 'M');
INSERT INTO Personal  values (1267, 3, 1, 8, 'JOAQUIN JAVIER', 'NUEVO', 'CARRETO', 'M');
INSERT INTO Personal  values (1268, 2, 4, 10, 'EDIE', 'GALARZA', 'CHORENO', 'M');
INSERT INTO Personal  values (1269, 5, 14, 10, 'LUIS RAFAEL', 'FORTUNA', 'CUADRAS', 'M');
INSERT INTO Personal  values (1270, 6, 1, 2, 'GERMAIN', 'JUPAMEA', 'MENDIVIL', 'F');
INSERT INTO Personal  values (1271, 5, 12, 11, 'JOSE AGUSTIN', 'PATRICIA', 'PATATUCHI', 'F');
INSERT INTO Personal  values (1272, 9, 9, 9, 'RICARDO FELIPE', 'ANALCO', 'ITURBIDE', 'M');
INSERT INTO Personal  values (1273, 9, 2, 5, 'MARCO ALFREDO', 'CANDIA', 'COSTILLA', 'M');
INSERT INTO Personal  values (1274, 2, 11, 13, 'OMAR ALEJANDRO', 'CAEZ', 'SIAEZ', 'M');
INSERT INTO Personal  values (1275, 3, 11, 3, 'MARIA MAGDALENA', 'COLADO', 'AGUILERA', 'M');
INSERT INTO Personal  values (1276, 7, 9, 1, 'GUSTAVO ALFREDO', 'ENCALADA', 'MAON', 'F');
INSERT INTO Personal  values (1277, 9, 2, 2, 'LAMBERTO', 'ZARUR', 'PITALUA', 'M');
INSERT INTO Personal  values (1278, 4, 11, 7, 'JOSE IRAM', 'BOUTTIER', 'PALOMEQUE', 'F');
INSERT INTO Personal  values (1279, 9, 6, 4, 'LUIS LAURO', 'GRANILLO', 'TUYIN', 'M');
INSERT INTO Personal  values (1280, 1, 4, 12, 'JOSE MELCHOR', 'MARTINA', 'ATRISCO', 'F');
INSERT INTO Personal  values (1281, 9, 15, 4, 'JORGE LORENZO', 'RIEGO', 'IXBA', 'M');
INSERT INTO Personal  values (1282, 4, 14, 11, 'CARLOS ESTEBAN', 'RECIO', 'SARAOZ', 'M');
INSERT INTO Personal  values (1283, 3, 11, 11, 'SAUL ANTONIO', 'MISS', 'ALDAPA', 'F');
INSERT INTO Personal  values (1284, 9, 15, 4, 'HECTOR ALEJAND', 'SAGAON', 'ELIZARRARAS', 'M');
INSERT INTO Personal  values (1285, 9, 12, 8, 'OSCAR XAVIER', 'ITURRALDE', 'CAHERO', 'M');
INSERT INTO Personal  values (1286, 2, 2, 11, 'RUDI', 'BARCELO', 'IRACHETA', 'F');
INSERT INTO Personal  values (1287, 1, 4, 4, 'LUIS ULISES', 'LLAVE', 'PANO', 'F');
INSERT INTO Personal  values (1288, 5, 15, 8, 'AZAEL', 'AVITUA', 'DEL PILAR', 'F');
INSERT INTO Personal  values (1289, 7, 7, 4, 'OSCAR HUMBERTO', 'BENAVIDEZ', 'VILLELA', 'M');
INSERT INTO Personal  values (1290, 1, 15, 12, 'ESAU', 'OZUMBILLA', 'URDIERA', 'M');
INSERT INTO Personal  values (1291, 3, 7, 6, 'ISAAC', 'BURBOA', 'MORAN', 'M');
INSERT INTO Personal  values (1292, 3, 10, 9, 'LUIS ENRIQ', 'MATURIN', 'SANTIZ', 'F');
INSERT INTO Personal  values (1293, 8, 1, 10, 'RAUL LEONEL', 'COYOTE', 'NOGUERON', 'M');
INSERT INTO Personal  values (1294, 10, 2, 2, 'CANDELARIO', 'GUARDIAN', 'TLELO', 'M');
INSERT INTO Personal  values (1295, 9, 5, 12, 'ASAEL', 'COCOTLE', 'CHAVOLLA', 'M');
INSERT INTO Personal  values (1296, 10, 8, 9, 'J. SALVADOR', 'ACHACH', 'COVARRUBIO', 'M');
INSERT INTO Personal  values (1297, 3, 12, 8, 'GELACIO', 'VEJAR', 'LAREDO', 'F');
INSERT INTO Personal  values (1298, 6, 8, 1, 'FIDEL ARTURO', 'CUAJICALCO', 'MOJON', 'F');
INSERT INTO Personal  values (1299, 5, 13, 4, 'JUAN RAYMUNDO', 'GERONES', 'ERASTO', 'M');
INSERT INTO Personal  values (1300, 8, 1, 5, 'ADELAIDO', 'CARLO', 'VENEROSO', 'M');
INSERT INTO Personal  values (1301, 9, 13, 6, 'JESUS GERARDO', 'PLASENCIA', 'COSETL', 'M');
INSERT INTO Personal  values (1302, 6, 8, 13, 'EDGAR ISMAEL', 'HERNNDEZ', 'NOGUEZ', 'F');
INSERT INTO Personal  values (1303, 1, 10, 8, 'JESUS JONATHAN', 'MIXTECO', 'LAMADRID', 'M');
INSERT INTO Personal  values (1304, 1, 14, 12, 'ANTULIO', 'AGUIRRE', 'PARRAL', 'M');
INSERT INTO Personal  values (1305, 9, 9, 13, 'JESUS SAUL', 'ORPINEL', 'SAENS', 'M');
INSERT INTO Personal  values (1306, 9, 5, 1, 'ELIGIO', 'RETIZ', 'NAFATE', 'M');
INSERT INTO Personal  values (1307, 10, 9, 13, 'CARLOS ERNESTO', 'CORDOVA', 'TECO', 'F');
INSERT INTO Personal  values (1308, 6, 6, 6, 'MARTIN ADRIAN', 'BRAVO', 'HUERTAS', 'F');
INSERT INTO Personal  values (1309, 1, 4, 2, 'CARLOS RODRIGO', 'ACUA', 'Y CAN', 'M');
INSERT INTO Personal  values (1310, 6, 5, 12, 'RENE IVAN', 'QUINTAL', 'ZAPOTITLA', 'F');
INSERT INTO Personal  values (1311, 4, 13, 11, 'FAUSTINO', 'LARA', 'PAYEN', 'F');
INSERT INTO Personal  values (1312, 10, 9, 7, 'EDELMIRO', 'SUMANO', 'PALMER', 'M');
INSERT INTO Personal  values (1313, 9, 9, 4, 'JOAQUIN JESUS', 'CASTA!ON', 'FERRIO', 'M');
INSERT INTO Personal  values (1314, 4, 9, 7, 'ANGEL FERNANDO', 'SEGURA', 'TEPEQUE', 'M');
INSERT INTO Personal  values (1315, 7, 15, 3, 'ANDRES ALBERTO', 'VIVES', 'SILVIANO', 'F');
INSERT INTO Personal  values (1316, 5, 3, 10, 'JOSE EMANUEL', 'ASSAD', 'MONICA', 'F');
INSERT INTO Personal  values (1317, 4, 5, 2, 'ISRRAEL', 'EXCELENTE', 'RONZON', 'M');
INSERT INTO Personal  values (1318, 3, 14, 8, 'HUGO DANIEL', 'VQUEZ', 'AVI%A', 'M');
INSERT INTO Personal  values (1319, 4, 4, 5, 'JAVIER FRANCISCO', 'SILERIO', 'CAZALES', 'M');
INSERT INTO Personal  values (1320, 2, 3, 5, 'ANDRES MANUEL', 'CUATETA', 'ALDANA', 'M');
INSERT INTO Personal  values (1321, 5, 11, 10, 'JOSEFINA', 'VILLALANA', 'VISCARRA', 'F');
INSERT INTO Personal  values (1322, 7, 9, 11, 'SERAFIN', 'CHAIREZ', 'CENTENO', 'M');
INSERT INTO Personal  values (1323, 4, 1, 13, 'JESUS', 'MUNGARRO', 'VELAZCO', 'F');
INSERT INTO Personal  values (1324, 8, 10, 13, 'JUAN ABRAHAM', 'ARMEAGA', 'YECTLI', 'M');
INSERT INTO Personal  values (1325, 5, 1, 13, 'RUTILIO', 'TAVAREZ', 'CUPIDO', 'M');
INSERT INTO Personal  values (1326, 2, 2, 4, 'LEONIDES', 'PASOS', 'OSORIO', 'F');
INSERT INTO Personal  values (1327, 1, 9, 10, 'JAVIER ANGEL', 'DESION', 'CASSIO', 'M');
INSERT INTO Personal  values (1328, 6, 5, 9, 'ERNESTO ANTONIO', 'MARINELARENA', 'OVALLE', 'F');
INSERT INTO Personal  values (1329, 5, 14, 9, 'PROCOPIO', 'AMAVISCA', 'BERDEJO', 'M');
INSERT INTO Personal  values (1330, 2, 1, 2, 'JESUS FLORENTINO', 'AVI%A', 'MUNOZ', 'F');
INSERT INTO Personal  values (1331, 7, 13, 2, 'JUAN FRANCISCO', 'CARMELO', 'CHATU', 'F');
INSERT INTO Personal  values (1332, 2, 3, 3, 'OMAR GILBERTO', 'CUAXOSPA', 'LAUREANO', 'F');
INSERT INTO Personal  values (1333, 2, 7, 6, 'CARLOS TRINIDAD', 'CARAVANTES', 'MIXCOATL', 'F');
INSERT INTO Personal  values (1334, 10, 10, 2, 'JOSE EDGAR', 'REYNAGA', 'HERVER', 'F');
INSERT INTO Personal  values (1335, 4, 4, 2, 'IGNACIO MANUEL', 'H', 'SANJURJO', 'F');
INSERT INTO Personal  values (1336, 4, 3, 6, 'FRANCISCO JAVI', 'LOZADA', 'GUEROLA', 'M');
INSERT INTO Personal  values (1337, 1, 10, 10, 'JEAN PAUL', 'QUILES', 'MALIACHI', 'F');
INSERT INTO Personal  values (1338, 7, 8, 5, 'RAUL ELIAS', 'ORDOEZ', 'VALLESTEROS', 'F');
INSERT INTO Personal  values (1339, 7, 3, 8, 'JUAN HIPOLITO', 'AYERDE', 'MARICHE', 'F');
INSERT INTO Personal  values (1340, 1, 14, 2, 'RUBIEL', 'YAXI', 'ABREO', 'M');
INSERT INTO Personal  values (1341, 6, 1, 1, 'ANDRES DE JESUS', 'FERRAEZ', 'GINES', 'F');
INSERT INTO Personal  values (1342, 3, 5, 6, 'JORGE OSCAR', 'MERCHANT', 'NARVAEZ', 'F');
INSERT INTO Personal  values (1343, 4, 15, 8, 'VICTOR MAN', 'QUEJ', 'AYANEGUI', 'F');
INSERT INTO Personal  values (1344, 5, 4, 9, 'SERGIO ALEJANDRO', 'CASTILLEJOS', 'PRIOR', 'F');
INSERT INTO Personal  values (1345, 1, 9, 10, 'YASSER', 'OBE', 'PORFIRIO', 'F');
INSERT INTO Personal  values (1346, 10, 11, 2, 'CIRILO', 'VICHIQUE', 'ANIMA', 'F');
INSERT INTO Personal  values (1347, 2, 1, 5, 'LORETO', 'M. DEL CAMPO', 'ARMIDA', 'M');
INSERT INTO Personal  values (1348, 5, 5, 2, 'FERNANDO MIGUEL', 'MESTIZA', 'TEPOX', 'M');
INSERT INTO Personal  values (1349, 7, 1, 2, 'JUAN VICENTE', 'DOMINGO', 'DUENAS', 'F');
INSERT INTO Personal  values (1350, 9, 15, 6, 'SILVIANO', 'EUAN', 'BORBON', 'M');
INSERT INTO Personal  values (1351, 9, 15, 6, 'ALEJANDRO', 'GUENDULAY', 'LANZAGORTA', 'F');
INSERT INTO Personal  values (1352, 6, 8, 10, 'JAIME LUIS', 'GAMUNDI', 'COVIS', 'F');
INSERT INTO Personal  values (1353, 9, 1, 12, 'ALEJANDRO GUADALUPE', 'DEARA', 'PAYAN', 'F');
INSERT INTO Personal  values (1354, 8, 3, 10, 'JOSE MAURO', 'GALVES', 'BERMUDEZ', 'M');
INSERT INTO Personal  values (1355, 5, 4, 4, 'J. MATILDE', 'CUELLAR', 'TEROVA', 'M');
INSERT INTO Personal  values (1356, 9, 9, 6, 'JUAN ERASMO', 'ALDUENDA', 'EMIGDIO', 'M');
INSERT INTO Personal  values (1357, 6, 9, 8, 'JOSE ERIK', 'SENCION', 'LAZCANO', 'F');
INSERT INTO Personal  values (1358, 6, 10, 6, 'OSCAR DANIEL', 'MAQUEO', 'SANDIN', 'M');
INSERT INTO Personal  values (1359, 5, 10, 11, 'ALEJANDRO JAVIER', 'TORIS', 'DEL ALTO', 'F');
INSERT INTO Personal  values (1360, 3, 5, 1, 'REVERIANO', 'MUMENTHEY', 'BOLON', 'F');
INSERT INTO Personal  values (1361, 2, 4, 8, 'FROEBEL', 'MATIAS', 'GUANAJUATO', 'M');
INSERT INTO Personal  values (1362, 10, 2, 11, 'J ANTONIO', 'CONSUEGRA', 'PAT', 'M');
INSERT INTO Personal  values (1363, 3, 8, 3, 'ARBEY', 'AURIOLES', 'FREGOSO', 'M');
INSERT INTO Personal  values (1364, 4, 6, 1, 'JORGE GERARDO', 'LEANDRO', 'OCAϿA', 'F');
INSERT INTO Personal  values (1365, 9, 6, 8, 'JOSE LENIN', 'VALDEPEA', 'RASCON', 'F');
INSERT INTO Personal  values (1366, 5, 14, 4, 'JESUS ARIEL', 'CHALINI', 'OSCAR', 'M');
INSERT INTO Personal  values (1367, 9, 8, 13, 'JULIO JESUS', 'HOYOS', 'PENAGOS', 'F');
INSERT INTO Personal  values (1368, 4, 13, 12, 'EDGAR EMILIO', 'HERBERTH', 'COCOLETZI', 'M');
INSERT INTO Personal  values (1369, 4, 12, 11, 'TITO ARMANDO', 'VALDERRAMA', 'BALLEZA', 'F');
INSERT INTO Personal  values (1370, 3, 8, 3, 'REMBERTO', 'HAZA', 'ANTELO', 'F');
INSERT INTO Personal  values (1371, 6, 6, 8, 'MARIANO', 'AY', 'DE ALEJANDRO', 'M');
INSERT INTO Personal  values (1372, 3, 1, 1, 'FRANCISCO GABRIEL', 'GERON', 'LOOGEB', 'M');
INSERT INTO Personal  values (1373, 10, 8, 3, 'JOSE CORNELIO', 'BRACAMONTE', 'NOXPANCO', 'F');
INSERT INTO Personal  values (1374, 2, 7, 5, 'CASIANO', 'COSMES', 'CELAYA', 'M');
INSERT INTO Personal  values (1375, 4, 14, 7, 'EDGAR ARTURO', 'ZELOCUATECATL', 'FRANK', 'F');
INSERT INTO Personal  values (1376, 3, 15, 11, 'J JOSE', 'POMARES', 'CAT', 'F');
INSERT INTO Personal  values (1377, 9, 2, 10, 'GERARDO SALVADOR', 'RUANO', 'CUETO', 'M');
INSERT INTO Personal  values (1378, 8, 4, 13, 'FELIPE DE JE', 'CALDINO', 'LUQUEO', 'M');
INSERT INTO Personal  values (1379, 5, 8, 13, 'JOSE SERVANDO', 'ZULOAGA', 'RAUDALES', 'F');
INSERT INTO Personal  values (1380, 3, 8, 4, 'VICTOR SANTIAGO', 'STGO', 'AVELINO', 'F');
INSERT INTO Personal  values (1381, 9, 3, 13, 'VITALIANO', 'CARRIZALEZ', 'SANSORES', 'M');
INSERT INTO Personal  values (1382, 7, 8, 13, 'MARIO MANUEL', 'MALFITANO', 'ALONSO', 'F');
INSERT INTO Personal  values (1383, 7, 10, 13, 'DARINEL', 'PARTIDA', 'NAVIDAD', 'M');
INSERT INTO Personal  values (1384, 4, 10, 8, 'HENRY', 'FAJARDO', 'JOSEFA', 'M');
INSERT INTO Personal  values (1385, 7, 12, 13, 'RODOLFO DE JESUS', 'MUϿIZ', 'SAN MIGUEL', 'F');
INSERT INTO Personal  values (1386, 3, 11, 9, 'JOSE ALVARO', 'ALONZO', 'URRIETA', 'F');
INSERT INTO Personal  values (1387, 7, 12, 1, 'RENE', 'MAPULA', 'MARGALLI', 'M');
INSERT INTO Personal  values (1388, 7, 1, 5, 'NESTOR DAVID', 'OGAZ', 'CAMINO', 'M');
INSERT INTO Personal  values (1389, 7, 9, 13, 'EDGAR URIEL', 'BADAJOZ', 'ECHEVARRIA', 'F');
INSERT INTO Personal  values (1390, 7, 8, 11, 'PEDRO GERARDO', 'CERA', 'ALMEJO', 'F');
INSERT INTO Personal  values (1391, 7, 1, 10, 'ELIZABETH', 'OLIVIER', 'VILLAGOMEZ', 'F');
INSERT INTO Personal  values (1392, 3, 9, 13, 'GUILLERMO ALFREDO', 'DIONISIO', 'TRIAY', 'F');
INSERT INTO Personal  values (1393, 1, 3, 6, 'APOLO', 'SAHAGUN', 'BALDERRABANO', 'M');
INSERT INTO Personal  values (1394, 10, 1, 4, 'JESUS ELEAZAR', 'GRESS', 'ANGELA', 'M');
INSERT INTO Personal  values (1395, 6, 6, 2, 'SAUL FRANCISCO', 'VALLESTEROS', 'MUGICA', 'M');
INSERT INTO Personal  values (1396, 9, 12, 1, 'HUGO SALVADOR', 'FIGUEROA', 'URUENA', 'M');
INSERT INTO Personal  values (1397, 2, 14, 7, 'JOSE CRISTOBAL', 'TALIN', 'LOBERA', 'M');
INSERT INTO Personal  values (1398, 9, 1, 9, 'GUILLERMO ALEJANDRO', 'DESAIDA', 'BALSECA', 'M');
INSERT INTO Personal  values (1399, 7, 9, 7, 'HUGO FERNANDO', 'ZUNIGA', 'MEDA', 'M');
INSERT INTO Personal  values (1400, 5, 1, 11, 'EDGAR ARMANDO', 'ZIMBRON', 'MONTA%EZ', 'M');
INSERT INTO Personal  values (1401, 6, 4, 1, 'OSCAR GABRIEL', 'VIQUE', 'MAGA#A', 'M');
INSERT INTO Personal  values (1402, 1, 4, 5, 'ERICK', 'SILVAN', 'CHAZARI', 'M');
INSERT INTO Personal  values (1403, 5, 13, 3, 'LUIS NORBERTO', 'BECIEZ', 'CLAVIJO', 'F');
INSERT INTO Personal  values (1404, 6, 12, 10, 'LUIS EMMANUEL', 'DE LA MERCED', 'ALBARRAN', 'F');
INSERT INTO Personal  values (1405, 9, 15, 13, 'CARLOS EMMANUEL', 'CHALICO', 'ECHEVERRIA', 'F');
INSERT INTO Personal  values (1406, 6, 7, 13, 'FRANCISCO RODOLFO', 'GUARDIOLA', 'SULVARAN', 'M');
INSERT INTO Personal  values (1407, 10, 14, 10, 'JOSE ALEXANDER', 'ALFONZO', 'ENGUILO', 'M');
INSERT INTO Personal  values (1408, 3, 13, 4, 'ANGEL HUMBERTO', 'GOYTIA', 'SUGIA', 'F');
INSERT INTO Personal  values (1409, 3, 8, 4, 'JOVANY', 'MOHEDANO', 'SENCION', 'M');
INSERT INTO Personal  values (1410, 3, 15, 10, 'DANIEL OCTAVIO', 'POUMIAN', 'DERRAMADERO', 'F');
INSERT INTO Personal  values (1411, 8, 1, 6, 'FRANCISCO GREGORIO', 'LASCARES', 'ALDABA', 'F');
INSERT INTO Personal  values (1412, 3, 11, 2, 'LUIS AGUSTIN', 'J', 'CAPITAINE', 'F');
INSERT INTO Personal  values (1413, 7, 12, 4, 'ARIEL ALBERTO', 'TEZOCO', 'BASSO', 'M');
INSERT INTO Personal  values (1414, 3, 15, 6, 'HERVEY', 'Y RENDON', 'TRISTE', 'F');
INSERT INTO Personal  values (1415, 9, 5, 3, 'IDELFONSO', 'OATE', 'ALDAVA', 'M');
INSERT INTO Personal  values (1416, 5, 12, 6, 'JULIO HUMBERTO', 'EDEZA', 'MECALCO', 'M');
INSERT INTO Personal  values (1417, 10, 14, 3, 'JOSE MACARIO', 'CASQUERA', 'CANACASCO', 'F');
INSERT INTO Personal  values (1418, 6, 2, 2, 'JAVIER JESUS', 'INES', 'SANDOVAL', 'M');
INSERT INTO Personal  values (1419, 10, 7, 1, 'ERNESTO ALEJANDRO', 'CAMANO', 'MARISCALES', 'F');
INSERT INTO Personal  values (1420, 6, 9, 1, 'LUIS AURELIO', 'CUMPEAN', 'LAGUNEZ', 'M');
INSERT INTO Personal  values (1421, 3, 14, 10, 'ALBERTO RAMON', 'PILAR', 'SAMBERINO', 'M');
INSERT INTO Personal  values (1422, 6, 15, 4, 'FELIPE FRANCISCO', 'HUIDOBRO', 'VENEGAS', 'F');
INSERT INTO Personal  values (1423, 6, 2, 4, 'HECTOR GREGORIO', 'GAITAN', 'TEYER', 'M');
INSERT INTO Personal  values (1424, 1, 2, 1, 'MARIO ANGEL', 'ALCANTAR', 'LEEP', 'F');
INSERT INTO Personal  values (1425, 4, 8, 3, 'J. FELIX', 'TRAPERO', 'VIZGUERRA', 'F');
INSERT INTO Personal  values (1426, 8, 14, 10, 'FERNANDO CESAR', 'IRIARTE', 'BURGOIN', 'M');
INSERT INTO Personal  values (1427, 6, 8, 1, 'ROGELIO GUADALUPE', 'BA%UELOS', 'PERCASTEGUI', 'M');
INSERT INTO Personal  values (1428, 10, 14, 5, 'VICENTE ALEJANDRO', 'HARO', 'COMBERA', 'M');
INSERT INTO Personal  values (1429, 3, 13, 2, 'RUBEN JAVIER', 'JEREZ', 'BARDALES', 'M');
INSERT INTO Personal  values (1430, 1, 15, 4, 'GERARDO GABRIEL', 'ESPAIN', 'FORT', 'F');
INSERT INTO Personal  values (1431, 1, 4, 6, 'JOSE GASPAR', 'ALMEDA', 'TALAVERA', 'F');
INSERT INTO Personal  values (1432, 5, 13, 3, 'FAUSTO MANUEL', 'LOMA', 'RICO', 'M');
INSERT INTO Personal  values (1433, 6, 7, 1, 'SAUL EDUARDO', 'OLAIZ', 'TLALI', 'M');
INSERT INTO Personal  values (1434, 4, 2, 5, 'RAUL GUILLERMO', 'CAMEY', 'BARRUETA', 'F');
INSERT INTO Personal  values (1435, 1, 8, 3, 'CHRISTIAN EMMANUEL', 'MARCELINA', 'MERITO', 'M');
INSERT INTO Personal  values (1436, 8, 12, 6, 'MANUEL BERNARDO', 'MALLOZZI', 'NEVEROS', 'F');
INSERT INTO Personal  values (1437, 8, 6, 10, 'MEREGILDO', 'GORDON', 'MURRIETA', 'M');
INSERT INTO Personal  values (1438, 4, 8, 3, 'MANUEL SALVADOR', 'ELVIRA', 'BIZARRON', 'F');
INSERT INTO Personal  values (1439, 4, 7, 7, 'JOSE AMANDO', 'GONGORA', 'ARMAS', 'F');
INSERT INTO Personal  values (1440, 2, 7, 13, 'FRANCISCO JAVIER', 'PRESUEL', 'VALLADOLID', 'F');
INSERT INTO Personal  values (1441, 2, 13, 1, 'JOSE SILVERIO', 'ARRIOLA', 'GABIA', 'F');
INSERT INTO Personal  values (1442, 1, 5, 3, 'OLIVIO', 'EGREMI', 'BOLANOS', 'F');
INSERT INTO Personal  values (1443, 4, 9, 2, 'ARMANDO ANTONIO', 'MAYTORENA', 'REZA', 'M');
INSERT INTO Personal  values (1444, 3, 13, 9, 'CRUZ ENRIQUE', 'OLAY', 'PALMAS', 'M');
INSERT INTO Personal  values (1445, 7, 1, 4, 'JORGE OMAR', 'ZENON', 'IVAL', 'F');
INSERT INTO Personal  values (1446, 6, 8, 3, 'GERARDO ENRIQUE', 'CELIZ', 'ACALCO', 'M');
INSERT INTO Personal  values (1447, 2, 6, 13, 'SAUL ISAAC', 'GARAY', 'SALCIDO', 'F');
INSERT INTO Personal  values (1448, 6, 11, 4, 'JOSE VALENTE', 'LERDO', 'MUOZ', 'F');
INSERT INTO Personal  values (1449, 6, 15, 11, 'MARTIN NOE', 'CANDILA', 'GOROZTIETA', 'F');
INSERT INTO Personal  values (1450, 1, 12, 1, 'FRANCISCO RENE', 'CIPRIAN', 'GAZCON', 'M');
INSERT INTO Personal  values (1451, 9, 8, 13, 'OMAR DANIEL', 'ASENCIO', 'FRAUSTRO', 'M');
INSERT INTO Personal  values (1452, 3, 9, 12, 'MARCOS', 'PAJON', 'SALIGAN', 'F');
INSERT INTO Personal  values (1453, 5, 3, 11, 'MANUEL ALFONSO', 'ARAMBURO', 'VERDEL', 'M');
INSERT INTO Personal  values (1454, 1, 15, 5, 'WILSON', 'MELECIO', 'RAMIREZ', 'F');
INSERT INTO Personal  values (1455, 1, 2, 11, 'LONGINO', 'REVUELTA', 'GUATEMALA', 'F');
INSERT INTO Personal  values (1456, 8, 2, 13, 'JONATHAN ULISES', 'VILLAGOMEZ', 'UBIETA', 'F');
INSERT INTO Personal  values (1457, 7, 11, 11, 'WILIAN', 'URQUIN', 'TEPETATE', 'F');
INSERT INTO Personal  values (1458, 10, 10, 7, 'DAVID ROGELIO', 'URIOSTEGUI', 'MONTESINO', 'F');
INSERT INTO Personal  values (1459, 4, 15, 11, 'FELIX FERNANDO', 'CANABAL', 'ORTELA', 'F');
INSERT INTO Personal  values (1460, 1, 11, 4, 'FRANCISCO ISMAEL', 'CRISANTOS', 'CHAPA', 'M');
INSERT INTO Personal  values (1461, 8, 6, 9, 'JULIO OMAR', 'OCOTITLA', 'GRAJEDA', 'M');
INSERT INTO Personal  values (1462, 7, 3, 3, 'JESUS RENE', 'CLARO', 'UCH', 'F');
INSERT INTO Personal  values (1463, 1, 5, 1, 'JORGE DE JESUS', 'CATZIN', 'BAZAN', 'M');
INSERT INTO Personal  values (1464, 6, 2, 1, 'ESEQUIEL', 'MACEGOZA', 'VICENTE', 'M');
INSERT INTO Personal  values (1465, 8, 5, 4, 'RUBEN ALEJANDRO', 'SEGOVIANO', 'BRIONES', 'M');
INSERT INTO Personal  values (1466, 1, 10, 9, 'PEDRO MANUEL', 'AVELIZAPA', 'DOLORES', 'F');
INSERT INTO Personal  values (1467, 4, 11, 1, 'JORGE PEDRO', 'MUϿOA', 'SCHULTZ', 'M');
INSERT INTO Personal  values (1468, 8, 3, 10, 'RAMON HUMBERTO', 'OROCIO', 'MARCOS', 'M');
INSERT INTO Personal  values (1469, 4, 1, 3, 'JESUS JUAN', 'RUVALCABA', 'PAJARO', 'F');
INSERT INTO Personal  values (1470, 6, 6, 2, 'RENE EDUARDO', 'MONICA', 'ZABALZA', 'M');
INSERT INTO Personal  values (1471, 2, 10, 6, 'OMAR FERNANDO', 'CARRETO', 'BERNARDO', 'M');
INSERT INTO Personal  values (1472, 6, 3, 13, 'IGNACIO', 'KUMAN', 'OLIMON', 'M');
INSERT INTO Personal  values (1473, 5, 1, 6, 'GABINO', 'MORAGA', 'HINOSTROZA', 'M');
INSERT INTO Personal  values (1474, 10, 13, 8, 'MARIO EDMUNDO', 'CEH', 'VALLEJAN', 'F');
INSERT INTO Personal  values (1475, 5, 14, 6, 'DAVID ANGEL', 'MENECES', 'BALLI', 'F');
INSERT INTO Personal  values (1476, 7, 2, 10, 'MANUEL ISMAEL', 'ALMONTE', 'AYAQUICA', 'M');
INSERT INTO Personal  values (1477, 6, 10, 6, 'JOSE RITO', 'CANTARELL', 'BASULTO', 'F');
INSERT INTO Personal  values (1478, 2, 13, 13, 'LUIS ALFONSO', 'COLLINS', 'TZUN', 'M');
INSERT INTO Personal  values (1479, 10, 13, 9, 'MILTON JESUS', 'DONJUAN', 'CASTA?EDA', 'F');
INSERT INTO Personal  values (1480, 8, 1, 1, 'PEDRO MARCELINO', 'LOAEZA', 'VQUEZ', 'F');
INSERT INTO Personal  values (1481, 4, 9, 5, 'ISAIAS RAFAEL', 'OCELOTL', 'FRANCIA', 'M');
INSERT INTO Personal  values (1482, 2, 4, 4, 'LUIS ALVARO', 'LURIA', 'BETANZOS', 'F');
INSERT INTO Personal  values (1483, 6, 8, 13, 'GERARDO', 'PAYNO', 'PATATUCHI', 'F');
INSERT INTO Personal  values (1484, 10, 8, 11, 'PEDRO JORGE', 'DE LA TORRE', 'GOVEA', 'F');
INSERT INTO Personal  values (1485, 8, 15, 9, 'MARCOS GERARDO', 'SANTANA', 'SOTUYO', 'F');
INSERT INTO Personal  values (1486, 6, 2, 11, 'ANGEL GABRIEL', 'QUECHULPA', 'ESPIRICUETA', 'M');
INSERT INTO Personal  values (1487, 10, 14, 10, 'EDGAR JAVIER', 'ALDABA', 'CELEDON', 'F');
INSERT INTO Personal  values (1488, 9, 11, 7, 'VICTOR RAMON', 'MARANTO', 'CAPUCHINO', 'F');
INSERT INTO Personal  values (1489, 1, 12, 6, 'SERAFIN', 'DEFERIA', 'SERAFIN', 'M');
INSERT INTO Personal  values (1490, 7, 1, 9, 'RAFAEL ANTONIO', 'BENDITO', 'ALFONSO', 'F');
INSERT INTO Personal  values (1491, 4, 4, 12, 'SERGIO EDGAR', 'BOJORQUEZ', 'BATA', 'F');
INSERT INTO Personal  values (1492, 10, 1, 1, 'JOSE FELIX', 'ZERME%O', 'TOVAR', 'M');
INSERT INTO Personal  values (1493, 6, 7, 8, 'JOSE EDWIN', 'URTEAGA', 'LIZARDI', 'M');
INSERT INTO Personal  values (1494, 9, 15, 2, 'PABLO DAVID', 'GALAVIZ', 'Y AVILA', 'F');
INSERT INTO Personal  values (1495, 10, 9, 7, 'IRENEO', 'CUE', 'SIMONS', 'M');
INSERT INTO Personal  values (1496, 7, 1, 11, 'JOSE LAZARO', 'REYNOZO', 'SANTIZO', 'M');
INSERT INTO Personal  values (1497, 3, 4, 5, 'SATURNINO', 'GUIRADO', 'TIZNADO', 'F');
INSERT INTO Personal  values (1498, 8, 11, 6, 'MARIO ANTONIO', 'BERNAL', 'PINALES', 'M');
INSERT INTO Personal  values (1499, 4, 8, 10, 'AHUITZOTL', 'ARENA', 'TLALMIS', 'M');
INSERT INTO Personal  values (1500, 9, 13, 9, 'CARLOS ANTONIO', 'OTERO', 'LOM', 'F');
INSERT INTO Personal  values (1501, 10, 5, 13, 'CESAR EDGAR', 'ARONTES', 'OBLE', 'M');
INSERT INTO Personal  values (1502, 4, 11, 4, 'HUMBERTO ANTONIO', 'CEREZO', 'DE GANTE', 'F');
INSERT INTO Personal  values (1503, 3, 6, 1, 'IGNACIO MARTIN', 'CARDELL', 'ROQUEI', 'M');
INSERT INTO Personal  values (1504, 7, 1, 6, 'DANIEL ISAAC', 'VALENTINO', 'UTRILLA', 'M');
INSERT INTO Personal  values (1505, 10, 13, 10, 'JORGE RAFAEL', 'ALBARES', 'LOAIZA', 'M');
INSERT INTO Personal  values (1506, 9, 4, 6, 'EDUARDO ALONSO', 'VILIS', 'SABINO', 'F');
INSERT INTO Personal  values (1507, 10, 3, 2, 'JORGE FRANCISCO', 'JARQUIN', 'Y CABRERA', 'M');
INSERT INTO Personal  values (1508, 5, 14, 4, 'MARTIN SANTOS', 'YAHUACA', 'QUIJAS', 'M');
INSERT INTO Personal  values (1509, 5, 15, 11, 'JOSE DE LA CRUZ', 'TECOX', 'TEPATO', 'F');
INSERT INTO Personal  values (1510, 4, 12, 13, 'FRANCISCO RODOLFO', 'ANDUJO', 'TLILAYATZI', 'M');
INSERT INTO Personal  values (1511, 1, 8, 12, 'ARGIMIRO', 'MARCOS', 'VEYTIA', 'M');
INSERT INTO Personal  values (1512, 4, 7, 2, 'PRICILIANO', 'VALE', 'CRODA', 'F');
INSERT INTO Personal  values (1513, 4, 7, 6, 'CRISANTO', 'Y CAMPOS', 'PROCOPIO', 'F');
INSERT INTO Personal  values (1514, 1, 11, 11, 'EDUARDO IVAN', 'QUEJ', 'VALORA', 'M');
INSERT INTO Personal  values (1515, 1, 2, 1, 'HUGO FRANCISCO', 'TEPOX', 'DEL RAZO', 'M');
INSERT INTO Personal  values (1516, 6, 15, 11, 'DARVIN', 'SMER', 'PEQUEO', 'M');
INSERT INTO Personal  values (1517, 4, 10, 5, 'ALDO GABRIEL', 'MONTECILLO', 'BENAVIDES', 'F');
INSERT INTO Personal  values (1518, 9, 7, 8, 'FERNANDO OCTAVIO', 'V', 'FAUSTINOS', 'F');
INSERT INTO Personal  values (1519, 8, 4, 7, 'JOSE NELSON', 'PAULINO', 'FRANCES', 'F');
INSERT INTO Personal  values (1520, 8, 9, 11, 'NICODEMO', 'YLLESCAS', 'LIMETA', 'F');
INSERT INTO Personal  values (1521, 8, 5, 6, 'TORIBIO', 'COLLANTES', 'DENIS', 'F');
INSERT INTO Personal  values (1522, 7, 5, 8, 'SANTIAGO DE JESUS', 'VILLALAZ', 'CASTANEDA', 'M');
INSERT INTO Personal  values (1523, 9, 14, 10, 'FILIBERTO', 'ESCALON', 'ROMANO', 'M');
INSERT INTO Personal  values (1524, 2, 11, 11, 'ANDRES ENRIQUE', 'BRUSSOLO', 'MARCHANTE', 'F');
INSERT INTO Personal  values (1525, 4, 14, 5, 'FRANCISCO CARLOS', 'CHOPIN', 'COSTILLA', 'F');
INSERT INTO Personal  values (1526, 10, 4, 3, 'TOMAS ALBERTO', 'ROSALEZ', 'CEPEDA', 'M');
INSERT INTO Personal  values (1527, 9, 12, 6, 'CHRISTIAN OMAR', 'COMPA#', 'BAEZA', 'M');
INSERT INTO Personal  values (1528, 5, 6, 13, 'MARIO RIGOBERTO', 'OLAIZ', 'ESQUINCA', 'F');
INSERT INTO Personal  values (1529, 4, 14, 3, 'WILLIAM JESUS', 'OYERVIDES', 'OROSCO', 'F');
INSERT INTO Personal  values (1530, 7, 2, 4, 'ELVIRO', 'TECORRAL', 'RECALACHE', 'F');
INSERT INTO Personal  values (1531, 4, 12, 9, 'JUAN OCTAVIO', 'TALAMANTES', 'HUIPE', 'F');
INSERT INTO Personal  values (1532, 8, 11, 12, 'SOCORRO', 'BARTOLON', 'CANTO', 'F');
INSERT INTO Personal  values (1533, 9, 11, 3, 'JALIL', 'CAJUN', 'TEPETLAPA', 'M');
INSERT INTO Personal  values (1534, 3, 12, 13, 'ZENON', 'ACOLT', 'TRANI', 'F');
INSERT INTO Personal  values (1535, 2, 2, 5, 'SALVADOR GERARDO', 'BRIZO', 'CANDANOZA', 'F');
INSERT INTO Personal  values (1536, 7, 12, 10, 'RAFAEL ARMANDO', 'FERNANDEZ DE LARA', 'URGELL', 'F');
INSERT INTO Personal  values (1537, 2, 2, 4, 'JOSE CRUZ', 'VILLAFAA', 'DIAZ', 'F');
INSERT INTO Personal  values (1538, 2, 5, 8, 'JESUS NICOLAS', 'BARILLAS', 'CUELLO', 'F');
INSERT INTO Personal  values (1539, 1, 13, 3, 'JAIME DAVID', 'MELQUIADES', 'ECHEGARAY', 'M');
INSERT INTO Personal  values (1540, 4, 15, 2, 'RAMON ALEJANDRO', 'VIZARRAGA', 'CUAUTLI', 'M');
INSERT INTO Personal  values (1541, 3, 1, 12, 'MARIO SAUL', 'CARRENO', 'BONIFAZ', 'M');
INSERT INTO Personal  values (1542, 10, 8, 3, 'ORBELIN', 'LANUZA', 'ZARATE', 'M');
INSERT INTO Personal  values (1543, 8, 9, 13, 'CARLOS ENRIQUE', 'DE LA ROCHA', 'MEAVE', 'F');
INSERT INTO Personal  values (1544, 4, 4, 5, 'OSCAR ARIEL', 'LINARTE', 'VILLAMAYOR', 'F');
INSERT INTO Personal  values (1545, 2, 1, 11, 'REMEDIOS', 'GONZALEZ', 'ESTRELLA', 'F');
INSERT INTO Personal  values (1546, 7, 8, 11, 'JORGE SAUL', 'BALDOVINOS', 'LONGINOS', 'F');
INSERT INTO Personal  values (1547, 2, 11, 6, 'ROBERT', 'ESIQUIO', 'MOJARRAS', 'F');
INSERT INTO Personal  values (1548, 9, 13, 2, 'RAUL HUMBERTO', 'LANDAZURI', 'PINILLO', 'F');
INSERT INTO Personal  values (1549, 7, 10, 11, 'EDISON', 'NEGRIN', 'OQUIL', 'F');
INSERT INTO Personal  values (1550, 9, 2, 5, 'JOSE DE J', 'LAUREAN', 'VITE', 'F');
INSERT INTO Personal  values (1551, 1, 2, 10, 'HUITZILIHUITL', 'YAEZ', 'ALDACO', 'F');
INSERT INTO Personal  values (1552, 9, 13, 7, 'AGUSTIN MANUEL', 'ARRAZATE', 'CHIA', 'F');
INSERT INTO Personal  values (1553, 9, 7, 7, 'JOSE ELPIDIO', 'BOLAOS', 'HERBERT', 'M');
INSERT INTO Personal  values (1554, 7, 1, 4, 'OSMAR', 'GURRION', 'PRUDENCIANO', 'M');
INSERT INTO Personal  values (1555, 1, 3, 5, 'HUGO BENJAMIN', 'BARRUETA', 'SANTIAGO', 'F');
INSERT INTO Personal  values (1556, 1, 1, 10, 'OMAR GILBERTO', 'SARINANA', 'CANTUA', 'M');
INSERT INTO Personal  values (1557, 10, 4, 3, 'DANIEL GUADALUPE', 'PETO', 'YAϿEZ', 'M');
INSERT INTO Personal  values (1558, 8, 5, 8, 'ALAIN', 'AREVALOS', 'GUEVARA', 'F');
INSERT INTO Personal  values (1559, 5, 11, 4, 'CARLOS GABRIEL', 'VALDEZ', 'BERNES', 'M');
INSERT INTO Personal  values (1560, 8, 4, 3, 'MAURILIO', 'VALDEPEA', 'TLALMANALCO', 'F');
INSERT INTO Personal  values (1561, 2, 11, 8, 'JORGE IGNACIO', 'PEREYDA', 'CUA', 'M');
INSERT INTO Personal  values (1562, 6, 10, 4, 'CESAR ENRIQUE', 'DOMINGO', 'GOLDARACENA', 'M');
INSERT INTO Personal  values (1563, 2, 6, 5, 'MODESTO', 'URBINA', 'GARNICA', 'F');
INSERT INTO Personal  values (1564, 9, 4, 11, 'ENRIQUE DE JESUS', 'RAUDALES', 'OCA#A', 'M');
INSERT INTO Personal  values (1565, 5, 4, 13, 'JUAN BAUTISTA', 'TIQUE', 'SONDA', 'M');
INSERT INTO Personal  values (1566, 3, 5, 10, 'ERICK ALEJANDRO', 'BENET', 'SAMPIERI', 'M');
INSERT INTO Personal  values (1567, 8, 1, 1, 'CALEB', 'BOLANOS', 'BAUMAN', 'M');
INSERT INTO Personal  values (1568, 5, 15, 5, 'JUAN C', 'ESCOBAR', 'TOXTLE', 'F');
INSERT INTO Personal  values (1569, 1, 7, 11, 'PABLO GERARDO', 'ALE', 'OLAY', 'F');
INSERT INTO Personal  values (1570, 2, 13, 11, 'SALVADOR FRANCISCO', 'ANTELE', 'BOLOM', 'F');
INSERT INTO Personal  values (1571, 9, 13, 10, 'ROBINSON', 'CASIMIRO', 'ESPARZA', 'M');
INSERT INTO Personal  values (1572, 8, 7, 6, 'JOSE ROMUALDO', 'MINJAREZ', 'BALLESTEROS', 'F');
INSERT INTO Personal  values (1573, 6, 4, 9, 'ANTONIO JOSE', 'BUDAR', 'BLANCARTE', 'M');
INSERT INTO Personal  values (1574, 6, 3, 10, 'RAUL FERNANDO', 'MANZANILLA', 'MANCERA', 'F');
INSERT INTO Personal  values (1575, 7, 10, 11, 'PATRICIA', 'ALI', 'TERREROS', 'M');
INSERT INTO Personal  values (1576, 6, 2, 13, 'J LUZ', 'BESARES', 'CONSUEGRA', 'M');
INSERT INTO Personal  values (1577, 10, 6, 2, 'SERGIO ARTURO', 'CARCANO', 'ESPA%A', 'F');
INSERT INTO Personal  values (1578, 3, 11, 11, 'JOSE PAUL', 'HUAXIN', 'MIRON', 'F');
INSERT INTO Personal  values (1579, 2, 6, 10, 'FELIPE NERI', 'GACHUPIN', 'PENAFORT', 'M');
INSERT INTO Personal  values (1580, 7, 11, 10, 'ESTEBAN', 'CIME', 'BURGUETE', 'F');
INSERT INTO Personal  values (1581, 9, 12, 8, 'JAVIER ANTONIO', 'MONTA%O', 'DE ANDA', 'F');
INSERT INTO Personal  values (1582, 7, 3, 10, 'LUIS SANTIAGO', 'BURGOA', 'MURRIETA', 'F');
INSERT INTO Personal  values (1583, 4, 4, 4, 'MARCO ALBERTO', 'BELMONTES', 'CHAGOLLA', 'F');
INSERT INTO Personal  values (1584, 9, 7, 2, 'JOSE NICOLAS', 'CAMANO', 'BERZUNZA', 'F');
INSERT INTO Personal  values (1585, 9, 1, 7, 'DAVID EMMANUEL', 'TOMATZIN', 'RAFAEL', 'M');
INSERT INTO Personal  values (1586, 1, 6, 8, 'JULIO RENE', 'MARIEL', 'CALTZONTZIN', 'M');
INSERT INTO Personal  values (1587, 5, 10, 11, 'HECTOR JOEL', 'NANGUELU', 'BARCEINAS', 'F');
INSERT INTO Personal  values (1588, 2, 11, 12, 'JOSE EMMANUEL', 'ESPARRAGOZA', 'COB', 'M');
INSERT INTO Personal  values (1589, 2, 8, 2, 'JOSE MACARIO', 'ALACIO', 'GABALDON', 'F');
INSERT INTO Personal  values (1590, 6, 5, 4, 'JESUS TRINIDAD', 'ALVAREZ', 'IBARES', 'M');
INSERT INTO Personal  values (1591, 5, 6, 10, 'MANUEL GERARDO', 'RIBOTA', 'MONARCA', 'M');
INSERT INTO Personal  values (1592, 6, 5, 5, 'EDDY', 'IZAZAGA', 'PIVARAL', 'F');
INSERT INTO Personal  values (1593, 6, 2, 12, 'JESUS LUIS', 'BAROCIO', 'CINTA', 'F');
INSERT INTO Personal  values (1594, 1, 12, 7, 'EDUARDO ARTURO', 'VILLASEÿOR', 'OCH', 'F');
INSERT INTO Personal  values (1595, 5, 2, 8, 'JESUS OSCAR', 'RICA!O', 'DE MARCOS', 'M');
INSERT INTO Personal  values (1596, 9, 7, 8, 'ADAIR', 'RETA', 'ORDU!A', 'F');
INSERT INTO Personal  values (1597, 6, 11, 13, 'CESAR ARMANDO', 'GUENDOLAY', 'D', 'F');
INSERT INTO Personal  values (1598, 6, 3, 3, 'GERARDO ARIEL', 'CIFUENTES', 'CAHERO', 'M');
INSERT INTO Personal  values (1599, 6, 13, 10, 'NECTAR', 'PANCARDO', 'EUGENIO', 'F');
INSERT INTO Personal  values (1600, 2, 14, 11, 'MANUEL RUBEN', 'VERGIL', 'LEZMA', 'F');
INSERT INTO Personal  values (1601, 8, 10, 1, 'CARLOS PAUL', 'NUCAMENDI', 'SERDAN', 'F');
INSERT INTO Personal  values (1602, 1, 3, 10, 'JOSE EUGENIO', 'ARCEO', 'CHINCOYA', 'F');
INSERT INTO Personal  values (1603, 9, 7, 11, 'JESUS DANIEL', 'VALLEJOS', 'FRAGA', 'M');
INSERT INTO Personal  values (1604, 9, 2, 3, 'NESTOR MANUEL', 'ROVIROSA', 'LANTO', 'M');
INSERT INTO Personal  values (1605, 4, 7, 1, 'JORGE HILARIO', 'CHIMIL', 'PINTO', 'F');
INSERT INTO Personal  values (1606, 2, 12, 7, 'AZIEL', 'MADA', 'OMA!A', 'F');
INSERT INTO Personal  values (1607, 9, 2, 10, 'HECTOR FERNANDO', 'MEDELES', 'FERRAL', 'M');
INSERT INTO Personal  values (1608, 9, 9, 2, 'FERNANDO GUADALUPE', 'POPOMEYA', 'DUENAS', 'F');
INSERT INTO Personal  values (1609, 3, 3, 7, 'ANGELBERTO', 'BEH', 'BARAY', 'M');
INSERT INTO Personal  values (1610, 9, 8, 5, 'ANGEL JOSE', 'BROCA', 'ATRIANO', 'F');
INSERT INTO Personal  values (1611, 3, 3, 10, 'J INOCENTE', 'CASERES', 'XINGU', 'F');
INSERT INTO Personal  values (1612, 5, 8, 10, 'DE JESUS', 'COCON', 'AUROZA', 'F');
INSERT INTO Personal  values (1613, 7, 3, 3, 'J DAVID', 'LANGO', 'CABADA', 'M');
INSERT INTO Personal  values (1614, 3, 8, 2, 'JORGE VICENTE', 'ESCUDILLO', 'OROZCO', 'F');
INSERT INTO Personal  values (1615, 2, 15, 9, 'JUAN ALEJANDRO', 'MAJALCA', 'FELIX', 'F');
INSERT INTO Personal  values (1616, 6, 8, 8, 'ESTANISLAO', 'LEYVA', 'AHUEJOTE', 'F');
INSERT INTO Personal  values (1617, 2, 12, 12, 'ORFANEL', 'SALGUERO', 'SUMARRAGA', 'F');
INSERT INTO Personal  values (1618, 2, 7, 2, 'WILLIAN', 'PORTALES', 'ZULOAGA', 'F');
INSERT INTO Personal  values (1619, 10, 11, 8, 'RAFAEL ENRIQUE', 'ORIZAGA', 'DE BENITO', 'F');
INSERT INTO Personal  values (1620, 6, 1, 12, 'USBALDO', 'GERONIMO', 'NIGOA', 'F');
INSERT INTO Personal  values (1621, 2, 4, 4, 'AMBROCIO', 'MALPICA', 'FLEITES', 'M');
INSERT INTO Personal  values (1622, 6, 12, 7, 'CARLOS AURELIO', 'UDAVE', 'VIDAURRI', 'M');
INSERT INTO Personal  values (1623, 9, 7, 9, 'CESAR ROGELIO', 'LIEVANOS', 'ORELLAN', 'F');
INSERT INTO Personal  values (1624, 6, 3, 8, 'GUZMAN', 'MAYNEZ', 'HERNNADEZ', 'F');
INSERT INTO Personal  values (1625, 7, 1, 6, 'SOSIMO', 'TENTLE', 'ATENCIO', 'F');
INSERT INTO Personal  values (1626, 4, 2, 7, 'REGINALDO', 'ECO', 'CARAPIA', 'M');
INSERT INTO Personal  values (1627, 3, 6, 8, 'LIDIA', 'MICHAUS', 'ORDUNA', 'M');
INSERT INTO Personal  values (1628, 9, 4, 5, 'RENAN', 'YERBES', 'ROMULO', 'F');
INSERT INTO Personal  values (1629, 10, 3, 12, 'DIONICIO', 'PINON', 'DONMIGUEL', 'M');
INSERT INTO Personal  values (1630, 9, 13, 9, 'JUAN ALFONSO', 'MU%IZ', 'SABINA', 'M');
INSERT INTO Personal  values (1631, 6, 10, 7, 'URBANO', 'SAN', 'AYAR', 'F');
INSERT INTO Personal  values (1632, 10, 9, 9, 'HECTOR JAIME', 'ASSAD', 'MATIAZ', 'M');
INSERT INTO Personal  values (1633, 4, 10, 13, 'RICARDO DE JESUS', 'CONSUELO', 'URQUIZO', 'F');
INSERT INTO Personal  values (1634, 9, 8, 4, 'JOSE PATRICIO', 'ZUAREZ', 'LAFUENTE', 'M');
INSERT INTO Personal  values (1635, 7, 13, 10, 'JESUS LORENZO', 'PEϿATE', 'LLANES', 'F');
INSERT INTO Personal  values (1636, 10, 6, 7, 'JOSE GAMALIEL', 'MONTEMAYOR', 'CAMPECH', 'F');
INSERT INTO Personal  values (1637, 7, 3, 5, 'GUSTAVO SALVADOR', 'COLLINS', 'MACARIO', 'M');
INSERT INTO Personal  values (1638, 4, 1, 9, 'EDSON', 'MAS', 'DE LA ROCHA', 'F');
INSERT INTO Personal  values (1639, 1, 4, 7, 'LUIS MARIANO', 'PATRACA', 'CORZO', 'M');
INSERT INTO Personal  values (1640, 3, 3, 2, 'JOSE BONIFACIO', 'DE JESUS', 'BRIGIDO', 'F');
INSERT INTO Personal  values (1641, 8, 2, 5, 'HECTOR HORACIO', 'NARES', 'SOCORRO', 'F');
INSERT INTO Personal  values (1642, 3, 2, 5, 'CESAR ORLANDO', 'ZOLOETA', 'FITTA', 'M');
INSERT INTO Personal  values (1643, 3, 8, 11, 'JOSE SEVERIANO', 'MESINO', 'NAVEJAS', 'F');
INSERT INTO Personal  values (1644, 5, 13, 4, 'MANRIQUE', 'CORTINES', 'LAZARIN', 'M');
INSERT INTO Personal  values (1645, 1, 6, 12, 'ALEJANDRO RAFAEL', 'ATECPANECATL', 'MATEOS', 'F');
INSERT INTO Personal  values (1646, 5, 8, 7, 'MARTIN JOEL', 'KUYOC', 'MONTAO', 'M');
INSERT INTO Personal  values (1647, 3, 7, 12, 'JORGE FELIPE', 'CAMPILLO', 'CUMPEAN', 'F');
INSERT INTO Personal  values (1648, 7, 7, 9, 'LEONARDO DANIEL', 'PI!A', 'MARCHAND', 'F');
INSERT INTO Personal  values (1649, 10, 14, 7, 'NEOFITO', 'LASCANO', 'VALVERDE', 'F');
INSERT INTO Personal  values (1650, 2, 4, 11, 'RUBICEL', 'DEL MORAL', 'VENTOLERO', 'F');
INSERT INTO Personal  values (1651, 1, 1, 5, 'GERSON', 'PINACHO', 'WARIO', 'M');
INSERT INTO Personal  values (1652, 9, 7, 2, 'ROMULO', 'CRISOSTOMO', 'AGUIIGA', 'F');
INSERT INTO Personal  values (1653, 9, 3, 12, 'ENRIQUE OCTAVIO', 'ENCISO', 'TOLAMATL', 'F');
INSERT INTO Personal  values (1654, 4, 8, 7, 'GUSTAVO JAVIER', 'SANCHO', 'TONIX', 'F');
INSERT INTO Personal  values (1655, 10, 7, 5, 'OSCAR FEDERICO', 'AGUAS', 'JIMENEZ', 'M');
INSERT INTO Personal  values (1656, 6, 13, 12, 'DAMASO', 'HERRAN', 'TARANGO', 'F');
INSERT INTO Personal  values (1657, 3, 15, 10, 'OSIRIS', 'DORAME', 'CORTAZA', 'F');
INSERT INTO Personal  values (1658, 8, 1, 1, 'VENANCIO', 'CASTAϿON', 'CARRIZALEZ', 'M');
INSERT INTO Personal  values (1659, 2, 12, 3, 'ABEL ALEJANDRO', 'XALTENO', 'BAAS', 'F');
INSERT INTO Personal  values (1660, 5, 1, 3, 'JAHIR', 'ESPINAL', 'VACA', 'M');
INSERT INTO Personal  values (1661, 8, 11, 6, 'FELIPE DE JE', 'MANOATL', 'MIRO', 'F');
INSERT INTO Personal  values (1662, 6, 7, 3, 'FELIPE JAVIER', 'SEDE!O', 'OROCIO', 'M');
INSERT INTO Personal  values (1663, 7, 1, 4, 'HECTOR ROGELIO', 'SALOME', 'LLERENA', 'F');
INSERT INTO Personal  values (1664, 8, 3, 4, 'JESUS SALVADOR', 'MEDINA', 'HARRELL', 'M');
INSERT INTO Personal  values (1665, 2, 7, 9, 'RUBEN DE JESUS', 'NOE', 'SAUZA', 'M');
INSERT INTO Personal  values (1666, 1, 4, 11, 'JOSE EFREN', 'REATIGA', 'COVARRUBIO', 'M');
INSERT INTO Personal  values (1667, 6, 8, 3, 'ARIEL DE JESUS', 'ISUNZA', 'RABASA', 'M');
INSERT INTO Personal  values (1668, 6, 9, 3, 'ROGER DAVID', 'MEDEL', 'RAGA', 'F');
INSERT INTO Personal  values (1669, 5, 8, 11, 'FRANCISCO FILIBERTO', 'FRANCO', 'MANRA', 'M');
INSERT INTO Personal  values (1670, 6, 11, 1, 'JORGE VALENTE', 'TISNADO', 'MUNGARRO', 'F');
INSERT INTO Personal  values (1671, 4, 15, 1, 'ELESBAN', 'DIMAS', 'BARZALOBRE', 'M');
INSERT INTO Personal  values (1672, 1, 11, 12, 'MARTIN RAUL', 'ESQUER', 'SEGUNDO', 'M');
INSERT INTO Personal  values (1673, 4, 9, 13, 'FRANCISCO GUILLERMO', 'DESIDERIO', 'SEDEO', 'M');
INSERT INTO Personal  values (1674, 1, 13, 11, 'FELIX ENRIQUE', 'SENCION', 'FIMBRES', 'F');
INSERT INTO Personal  values (1675, 10, 15, 1, 'FELIPE FRANCISCO', 'VIGIL', 'RETANO', 'M');
INSERT INTO Personal  values (1676, 2, 3, 13, 'JUAN CESAR', 'CRISTEN', 'CALDIO', 'F');
INSERT INTO Personal  values (1677, 7, 1, 4, 'ALDO', 'RIVAS', 'COPADO', 'F');
INSERT INTO Personal  values (1678, 7, 12, 5, 'JUAN GABRIEL', 'PLATEROS', 'LASCANO', 'F');
INSERT INTO Personal  values (1679, 6, 14, 3, 'JOSE SALVADOR', 'QUI#ONES', 'TECPA', 'M');
INSERT INTO Personal  values (1680, 1, 8, 11, 'PEDRO ARIEL', 'CEJA', 'CASTILLERO', 'M');
INSERT INTO Personal  values (1681, 9, 4, 7, 'CHRISTIAN MANUEL', 'CAA', 'ROMANILLO', 'M');
INSERT INTO Personal  values (1682, 1, 1, 7, 'VICTOR ALONSO', 'ARREVILLAGA', 'MICHICOL', 'F');
INSERT INTO Personal  values (1683, 6, 15, 11, 'FRANCISCO SALVADOR', 'INTERIAN', 'VILDOZOLA', 'F');
INSERT INTO Personal  values (1684, 2, 15, 5, 'PROCOPIO', 'CANGAS', 'PLANCARTE', 'F');
INSERT INTO Personal  values (1685, 3, 5, 1, 'KENNY', 'CORDOBA', 'MOISES', 'F');
INSERT INTO Personal  values (1686, 4, 15, 6, 'FRANCISCO ARTURO', 'AVENDA!O', 'HIRALES', 'F');
INSERT INTO Personal  values (1687, 8, 14, 4, 'ALDO SERGIO', 'LOVILLO', 'IXMATLAHUA', 'F');
INSERT INTO Personal  values (1688, 7, 11, 8, 'QUETZALCOATL', 'CHATU', 'ALTO', 'F');
INSERT INTO Personal  values (1689, 8, 11, 1, 'OBET', 'VILLAFRANCA', 'VILLASANA', 'M');
INSERT INTO Personal  values (1690, 8, 14, 11, 'JESUS NORBERTO', 'DEL ROSAL', 'ANTERO', 'F');
INSERT INTO Personal  values (1691, 1, 8, 12, 'IVAN EDUARDO', 'CATETE', 'AGUILA', 'M');
INSERT INTO Personal  values (1692, 1, 11, 4, 'RABINDRANATH', 'SALINAS', 'MU#OZ', 'F');
INSERT INTO Personal  values (1693, 4, 1, 2, 'FRANCISCO EDUARDO', 'ARRONTE', 'CARDE%A', 'M');
INSERT INTO Personal  values (1694, 3, 13, 2, 'JORGE ISAAC', 'VIELMA', 'AMECA', 'M');
INSERT INTO Personal  values (1695, 6, 14, 12, 'MANUEL ERNESTO', 'ESTEBES', 'CARTAGENA', 'F');
INSERT INTO Personal  values (1696, 7, 14, 1, 'SILVERIO', 'FITTA', 'JAYME', 'F');
INSERT INTO Personal  values (1697, 7, 1, 3, 'ROGER ANTONIO', 'CANEPA', 'ALEGRE', 'F');
INSERT INTO Personal  values (1698, 3, 12, 3, 'JOSE MAN', 'SIGUENZA', 'LECOURTOIS', 'F');
INSERT INTO Personal  values (1699, 3, 8, 8, 'ENRIQUE', 'PEDROZA', 'ESCARZAGA', 'M');
INSERT INTO Personal  values (1700, 6, 3, 3, 'GREGORIO ALFONSO', 'GABRIEL', 'ARADILLAS', 'M');
INSERT INTO Personal  values (1701, 3, 14, 6, 'EDGAR GILBERTO', 'FRAZ', 'ALMARAS', 'M');
INSERT INTO Personal  values (1702, 3, 5, 3, 'MARIO GABRIEL', 'ESTRELLA', 'BANDA', 'F');
INSERT INTO Personal  values (1703, 2, 4, 6, 'JOSE ANT', 'MERCHANT', 'LUCIANO', 'F');
INSERT INTO Personal  values (1704, 7, 11, 9, 'EDUARDO DE JESUS', 'FLORENZANO', 'INIGUEZ', 'M');
INSERT INTO Personal  values (1705, 2, 5, 4, 'JOSE GUADALUPE', 'QUEVEDO', 'CAHUARE', 'F');
INSERT INTO Personal  values (1706, 8, 2, 3, 'RAFAEL MARTIN', 'BERROTERAN', 'LIGONIO', 'M');
INSERT INTO Personal  values (1707, 3, 4, 12, 'RODIBERTO', 'MILAN', 'ACERO', 'F');
INSERT INTO Personal  values (1708, 10, 1, 13, 'ANGEL TOMAS', 'MAQUEDA', 'MITRE', 'F');
INSERT INTO Personal  values (1709, 4, 8, 5, 'MANUEL ANGEL', 'BARJAU', 'ARAMBURO', 'M');
INSERT INTO Personal  values (1710, 10, 9, 5, 'HECTOR NOE', 'BROWN', 'GARITA', 'M');
INSERT INTO Personal  values (1711, 10, 3, 12, 'IGNACIO GERMAN', 'FILOMENO', 'RUZ', 'F');
INSERT INTO Personal  values (1712, 9, 14, 11, 'LUIS PABLO', 'BALAN', 'MAXIMINO', 'F');
INSERT INTO Personal  values (1713, 5, 10, 11, 'FRANCISCO ARMANDO', 'LARUMBE', 'MUÿIZ', 'M');
INSERT INTO Personal  values (1714, 7, 10, 4, 'MARIO JOSE', 'MORATO', 'NOGUERA', 'F');
INSERT INTO Personal  values (1715, 1, 4, 4, 'WILBERTH', 'MENESES', 'MARRERO', 'F');
INSERT INTO Personal  values (1716, 5, 12, 7, 'HUGO JOSE', 'MARISCALES', 'UH', 'M');
INSERT INTO Personal  values (1717, 2, 8, 5, 'MARIO HERNAN', 'GAVITO', 'CARMELO', 'F');
INSERT INTO Personal  values (1718, 1, 11, 1, 'ANGEL DAVID', 'OSNAYA', 'MACUIXTLE', 'F');
INSERT INTO Personal  values (1719, 8, 12, 13, 'GERARDO GUADALUPE', 'MARIN', 'PORRES', 'M');
INSERT INTO Personal  values (1720, 4, 7, 8, 'GERMAN', 'MAURICIO', 'TZINTZUN', 'M');
INSERT INTO Personal  values (1721, 7, 15, 3, 'ZABDIEL', 'LLAGUNO', 'DIONISIO', 'F');
INSERT INTO Personal  values (1722, 5, 13, 12, 'MARTINEZ', 'POMPA', 'QUINTAL', 'M');
INSERT INTO Personal  values (1723, 9, 3, 1, 'FELIPE SANTIAGO', 'LOE', 'SUBIAUR', 'F');
INSERT INTO Personal  values (1724, 9, 13, 12, 'ALDO ALEJANDRO', 'BAYPOLI', 'HIJAR', 'M');
INSERT INTO Personal  values (1725, 6, 2, 5, 'CESAR IGNACIO', 'DE LOS SANTOS', 'ROSSETE', 'F');
INSERT INTO Personal  values (1726, 7, 8, 12, 'NATANIEL', 'IC', 'FIJAR', 'M');
INSERT INTO Personal  values (1727, 9, 5, 8, 'DONATO', 'TABAREZ', 'CUERO', 'M');
INSERT INTO Personal  values (1728, 8, 10, 12, 'JAVIER ALONSO', 'ELIOSA', 'ZAVALIJA', 'M');
INSERT INTO Personal  values (1729, 4, 2, 7, 'FIDEL ARMANDO', 'CHINCOYA', 'FARRERA', 'F');
INSERT INTO Personal  values (1730, 1, 4, 12, 'JORGE MIGUEL', 'LLANAS', 'CUAMEA', 'M');
INSERT INTO Personal  values (1731, 9, 13, 5, 'RACIEL', 'SALITRE', 'ARECHIGA', 'M');
INSERT INTO Personal  values (1732, 8, 11, 1, 'VICENTE GUADALUPE', 'DE LA PEA', 'CHEGUE', 'F');
INSERT INTO Personal  values (1733, 2, 12, 2, 'ROBERTO CARLO', 'LATOURNERIE', 'AUCES', 'M');
INSERT INTO Personal  values (1734, 4, 4, 3, 'ROBERTO ARMANDO', 'RUVALCABA', 'DEHESA', 'M');
INSERT INTO Personal  values (1735, 4, 12, 7, 'SERGIO RODOLFO', 'TEXCUCANO', 'ESPRONCEDA', 'M');
INSERT INTO Personal  values (1736, 8, 11, 8, 'JULIO RAFAEL', 'CAMPECHE', 'BALLINAS', 'F');
INSERT INTO Personal  values (1737, 7, 15, 13, 'SERGIO ROBERTO', 'VALLADO', 'INCLAN', 'F');
INSERT INTO Personal  values (1738, 10, 2, 12, 'HUGO LEONEL', 'CERVIN', 'SALDAA', 'M');
INSERT INTO Personal  values (1739, 6, 7, 10, 'GUSTAVO ANTONIO', 'ROVIRA', 'YAHUACA', 'F');
INSERT INTO Personal  values (1740, 8, 14, 8, 'IGNACIO IVAN', 'GRAJALES', 'SALORIO', 'F');
INSERT INTO Personal  values (1741, 2, 15, 8, 'J JAIME', 'TEXIS', 'MOLINOS', 'M');
INSERT INTO Personal  values (1742, 1, 2, 13, 'J. ROSARIO', 'ZAMILPA', 'VIRGINIA', 'F');
INSERT INTO Personal  values (1743, 2, 2, 3, 'PEDRO ARTURO', 'AGUAZUL', 'CORALES', 'M');
INSERT INTO Personal  values (1744, 1, 14, 8, 'MANUEL ROMAN', 'REBOLLAR', 'IZUCAR', 'F');
INSERT INTO Personal  values (1745, 10, 1, 10, 'HECTOR ISRAEL', 'JALIFE', 'FILOBELLO', 'M');
INSERT INTO Personal  values (1746, 7, 4, 2, 'MARTIN EUSEBIO', 'GRANDA', 'TENA', 'M');
INSERT INTO Personal  values (1747, 1, 3, 5, 'LAMBERTO', 'MURIEDAS', 'GURGUA', 'M');
INSERT INTO Personal  values (1748, 7, 1, 6, 'VICTOR MANUE', 'MURRIETA', 'TEUTLE', 'M');
INSERT INTO Personal  values (1749, 2, 11, 3, 'JOSE NATIVIDAD', 'PE!UELA', 'SANTA ANA', 'F');
INSERT INTO Personal  values (1750, 1, 15, 10, 'SALVADOR ENRIQUE', 'MAGUEY', 'CEJA', 'F');
INSERT INTO Personal  values (1751, 9, 11, 2, 'JOSE VICENTE', 'DE ITA', 'ANGULO', 'F');
INSERT INTO Personal  values (1752, 7, 5, 1, 'FRANCISCO ERNESTO', 'CONSOSPO', 'LPEZ', 'F');
INSERT INTO Personal  values (1753, 5, 13, 2, 'ANDRES JESUS', 'CACERES', 'VIELMA', 'M');
INSERT INTO Personal  values (1754, 5, 3, 10, 'OSCAR OSWALDO', 'BATRES', 'GURRUSQUIETA', 'M');
INSERT INTO Personal  values (1755, 6, 6, 6, 'JOSE FERNAND', 'COLOHUA', 'PASTENES', 'M');
INSERT INTO Personal  values (1756, 7, 3, 7, 'J. FELIX', 'DE BENITO', 'LESSO', 'M');
INSERT INTO Personal  values (1757, 1, 6, 9, 'CRESCENCIO', 'MALACATE', 'MADERO', 'M');
INSERT INTO Personal  values (1758, 9, 10, 4, 'JESUS CANDELARIO', 'ZAMANO', 'GUARDIOLA', 'M');
INSERT INTO Personal  values (1759, 10, 6, 11, 'VICTOR AURELIO', 'NEGRETE', 'MIRANDA', 'F');
INSERT INTO Personal  values (1760, 6, 10, 7, 'ALFREDO GUADALUPE', 'ZU%IGA', 'XOCUA', 'M');
INSERT INTO Personal  values (1761, 7, 4, 1, 'JESUS ENRIQUE', 'LEONOR', 'ESPAIN', 'M');
INSERT INTO Personal  values (1762, 10, 4, 13, 'ODIN', 'ABAD', 'DIAZ DE LEON', 'F');
INSERT INTO Personal  values (1763, 9, 2, 12, 'FERNANDO FRANCISCO', 'BEJINES', 'CHATU', 'F');
INSERT INTO Personal  values (1764, 3, 3, 3, 'JOSUE GABRIEL', 'OTAEZ', 'BOLAOS', 'M');
INSERT INTO Personal  values (1765, 8, 11, 3, 'RAMON ALONSO', 'LOYDA', 'TENREIRO', 'F');
INSERT INTO Personal  values (1766, 7, 13, 13, 'FRANCISCO MANUEL', 'DERRAMONA', 'MACIN', 'F');
INSERT INTO Personal  values (1767, 8, 2, 9, 'ALEJANDRO CRUZ', 'GALINDREZ', 'ALDRETE', 'M');
INSERT INTO Personal  values (1768, 6, 7, 7, 'JORGE URIEL', 'LABRADOR', 'ADAN', 'M');
INSERT INTO Personal  values (1769, 1, 5, 9, 'JORGE IVAN', 'MONTOR', 'CUE', 'F');
INSERT INTO Personal  values (1770, 4, 7, 6, 'CESAR RAYMUNDO', 'GORZO', 'ABSALON', 'M');
INSERT INTO Personal  values (1771, 6, 14, 10, 'RUBEN ALEJANDRO', 'KIN', 'APOSTOL', 'F');
INSERT INTO Personal  values (1772, 1, 4, 3, 'CESAR ARIEL', 'GINES', 'REQUENES', 'M');
INSERT INTO Personal  values (1773, 8, 5, 4, 'JOSE ROSARIO', 'SEBA', 'CHOPIN', 'F');
INSERT INTO Personal  values (1774, 1, 11, 3, 'JOSE HIPOLITO', 'ECHAVARRI', 'LLANO', 'M');
INSERT INTO Personal  values (1775, 10, 9, 4, 'OSCAR DE JESUS', 'JAIME', 'MANON', 'F');
INSERT INTO Personal  values (1776, 3, 12, 11, 'MARTIN ANDRES', 'CUICAS', 'ALBA', 'F');
INSERT INTO Personal  values (1777, 1, 10, 1, 'RICARDO ALONSO', 'ARREDONDO', 'ANDREZ', 'M');
INSERT INTO Personal  values (1778, 3, 14, 3, 'EFIGENIO', 'BALCON', 'SABAH', 'M');
INSERT INTO Personal  values (1779, 5, 6, 1, 'ANDRES MARTIN', 'CARDONA', 'PLACENCIA', 'F');
INSERT INTO Personal  values (1780, 1, 2, 2, 'HUGO JAVIER', 'SALDIERNA', 'MONTUFAR', 'F');
INSERT INTO Personal  values (1781, 9, 13, 3, 'RICARDO ANDRES', 'VILLAURRUTIA', 'COLLANTES', 'M');
INSERT INTO Personal  values (1782, 9, 5, 11, 'HECTOR EVERARDO', 'ISASSI', 'CHAC', 'M');
INSERT INTO Personal  values (1783, 1, 11, 7, 'VICTOR GERARDO', 'NAREDO', 'MUKUL', 'F');
INSERT INTO Personal  values (1784, 1, 9, 2, 'LIZANDRO', 'JUANDIEGO', 'ZITLALPOPOCATL', 'F');
INSERT INTO Personal  values (1785, 9, 10, 3, 'MAXIMINO', 'COY', 'ARMENDARIS', 'M');
INSERT INTO Personal  values (1786, 6, 5, 1, 'IVAN EMMANUEL', 'ROCAFUERTE', 'DOMINGA', 'M');
INSERT INTO Personal  values (1787, 4, 12, 3, 'JUAN ADRIAN', 'BENOSO', 'BOTE', 'M');
INSERT INTO Personal  values (1788, 4, 14, 7, 'ANGEL CUSTODIO', 'FIGAROLA', 'TEROVA', 'F');
INSERT INTO Personal  values (1789, 8, 10, 2, 'RAUL ARTURO', 'IZABAL', 'RABAGO', 'M');
INSERT INTO Personal  values (1790, 4, 6, 5, 'EDGAR RAUL', 'NAHON', 'DIONICIO', 'F');
INSERT INTO Personal  values (1791, 10, 1, 11, 'LUIS MIGUEL', 'NAMBO', 'DURAND', 'F');
INSERT INTO Personal  values (1792, 3, 6, 10, 'JESUS CESAR', 'ACHO', 'CAAMAR', 'M');
INSERT INTO Personal  values (1793, 2, 12, 1, 'WILBERTH ANTONIO', 'XELHUANTZI', 'SOLORIO', 'F');
INSERT INTO Personal  values (1794, 10, 3, 8, 'JOSE MERCED', 'PEREIDA', 'TOMAS', 'M');
INSERT INTO Personal  values (1795, 8, 7, 6, 'GERARDO HUMBERTO', 'COLUMNA', 'GONZLEZ', 'F');
INSERT INTO Personal  values (1796, 5, 10, 3, 'FRANCISCO FABIAN', 'TEUTLI', 'ARVAYO', 'F');
INSERT INTO Personal  values (1797, 9, 12, 11, 'JOSE APOLONIO', 'MATURANO', 'ANGUAS', 'F');
INSERT INTO Personal  values (1798, 1, 15, 5, 'PAULO SERGIO', 'KANTER', 'OVANDO', 'M');
INSERT INTO Personal  values (1799, 5, 4, 8, 'GEOVANNY', 'HARRISON', 'SABANERO', 'F');
INSERT INTO Personal  values (1800, 9, 10, 13, 'FELIX ALEJANDRO', 'ALCOCER', 'BERNAL', 'M');
INSERT INTO Personal  values (1801, 6, 10, 11, 'MIGUEL MARTIN', 'OXIMEA', 'PUIG', 'F');
INSERT INTO Personal  values (1802, 1, 10, 2, 'ERIC RENE', 'BARRETERO', 'TZAKUN', 'F');
INSERT INTO Personal  values (1803, 9, 2, 13, 'ISAURO', 'BERAIN', 'NANGULARI', 'F');
INSERT INTO Personal  values (1804, 8, 13, 10, 'JORGE TOMAS', 'AMILPA', 'IXTEPAN', 'M');
INSERT INTO Personal  values (1805, 8, 6, 5, 'AUSENCIO', 'ESTILLADO', 'DAMASO', 'F');
INSERT INTO Personal  values (1806, 9, 13, 9, 'MARIO ALEJANDRO', 'TIBURCIO', 'CERMENO', 'M');
INSERT INTO Personal  values (1807, 5, 15, 9, 'JOSE TEOFILO', 'BOUCHAN', 'ROQUE', 'F');
INSERT INTO Personal  values (1808, 1, 15, 11, 'HECTOR ALBERTO', 'CALZADA', 'VILLAFRANCO', 'M');
INSERT INTO Personal  values (1809, 4, 14, 6, 'JEZIEL', 'MONTES', 'MENES', 'F');
INSERT INTO Personal  values (1810, 3, 13, 9, 'JORGE ARMANDO', 'TLETLEPANTZI', 'TROLLE', 'F');
INSERT INTO Personal  values (1811, 5, 12, 2, 'JORGE ISAIAS', 'DE CASTILLA', 'QUIAHUA', 'M');
INSERT INTO Personal  values (1812, 10, 6, 9, 'MARIO MARTIN', 'PINILLO', 'VISCARRA', 'F');
INSERT INTO Personal  values (1813, 1, 9, 4, 'JOSE IGNACIO', 'LLANO', 'LUISA', 'M');
INSERT INTO Personal  values (1814, 3, 14, 13, 'GODOFREDO', 'GIBERT', 'CORELLA', 'M');
INSERT INTO Personal  values (1815, 8, 12, 6, 'LUIS GABRIEL', 'SALVADOR', 'AHUATZIN', 'M');
INSERT INTO Personal  values (1816, 5, 6, 12, 'PRIMO', 'MAYORAL', 'GARDU!O', 'F');
INSERT INTO Personal  values (1817, 6, 9, 10, 'BACILIO', 'NIAVES', 'TOSTADO', 'F');
INSERT INTO Personal  values (1818, 1, 4, 12, 'EDGAR LEONEL', 'VILLARAUZ', 'PAZARAN', 'F');
INSERT INTO Personal  values (1819, 8, 10, 7, 'JAIME FRANCISCO', 'CUAUTLI', 'JABALERA', 'F');
INSERT INTO Personal  values (1820, 2, 3, 3, 'PEREZ', 'BARBABOSA', 'SANDRE', 'F');
INSERT INTO Personal  values (1821, 6, 14, 2, 'VICTOR DE JESUS', 'MONRROY', 'VIGUERIA', 'F');
INSERT INTO Personal  values (1822, 5, 11, 5, 'JOSE FERNANDO', 'LICON', 'CHULIM', 'M');
INSERT INTO Personal  values (1823, 2, 6, 3, 'ALFREDO ALEJANDRO', 'DEGALES', 'ROSAGEL', 'M');
INSERT INTO Personal  values (1824, 8, 15, 9, 'DANILO', 'RICARIO', 'YUCUPICIO', 'M');
INSERT INTO Personal  values (1825, 1, 8, 10, 'IROEL', 'NOTARIO', 'IGLECIAS', 'F');
INSERT INTO Personal  values (1826, 3, 5, 5, 'MANUEL IGNACIO', 'MARCELIN', 'SUSANO', 'M');
INSERT INTO Personal  values (1827, 5, 13, 8, 'JOSE JESUS', 'YEH', 'HERVER', 'F');
INSERT INTO Personal  values (1828, 3, 10, 7, 'DANIEL', 'BARBOSA', 'YOPIHUA', 'F');
INSERT INTO Personal  values (1829, 9, 15, 1, 'JOSE ALONSO', 'ADAME', 'TETLACUILO', 'M');
INSERT INTO Personal  values (1830, 5, 10, 7, 'JORGE BENITO', 'RAYO', 'BACAB', 'F');
INSERT INTO Personal  values (1831, 7, 4, 13, 'JESUS AARON', 'ORTA', 'DERRAMONA', 'F');
INSERT INTO Personal  values (1832, 8, 9, 11, 'JAVIER ABRAHAM', 'SANMARTIN', 'URDAPILLETA', 'M');
INSERT INTO Personal  values (1833, 4, 4, 1, 'PATRICIO', 'CHONCOA', 'TRENADO', 'F');
INSERT INTO Personal  values (1834, 4, 10, 1, 'MARCO AURELIO', 'Y GERON', 'BOLAOS', 'F');
INSERT INTO Personal  values (1835, 6, 8, 11, 'CESAR MANUEL', 'PORTAL', 'QUEBRADO', 'F');
INSERT INTO Personal  values (1836, 3, 9, 9, 'DOLORES', 'ROSILES', 'LOCIA', 'F');
INSERT INTO Personal  values (1837, 5, 10, 5, 'EFRAIN ALEJANDRO', 'BAUTISTA', 'GUEMEZ', 'F');
INSERT INTO Personal  values (1838, 7, 10, 9, 'PEDRO FRANCISCO', 'LANDEROS', 'ESCARTIN', 'M');
INSERT INTO Personal  values (1839, 5, 6, 8, 'MISSAEL', 'IDELFONSO', 'MERLA', 'M');
INSERT INTO Personal  values (1840, 10, 10, 13, 'JOSE FREDDY', 'BESAREZ', 'ALMEDA', 'M');
INSERT INTO Personal  values (1841, 5, 4, 5, 'TERESO DE JESUS', 'BEULO', 'MESTA', 'F');
INSERT INTO Personal  values (1842, 4, 9, 7, 'EDGAR BENJAMIN', 'COUOH', 'FAJARDO', 'M');
INSERT INTO Personal  values (1843, 10, 15, 10, 'JOSE FIDENCIO', 'DE LA MORA', 'NEGROE', 'M');
INSERT INTO Personal  values (1844, 4, 5, 4, 'PAVEL', 'ANDUEZA', 'JAVIER', 'M');
INSERT INTO Personal  values (1845, 6, 11, 5, 'RAUNEL', 'LAVEAGA', 'TLAZOLA', 'F');
INSERT INTO Personal  values (1846, 6, 7, 8, 'RAUL ALBERTO', 'TECOLAPA', 'VILLAFRANCA', 'M');
INSERT INTO Personal  values (1847, 8, 4, 5, 'J EDUARDO', 'VIEDMA', 'SANTANA', 'F');
INSERT INTO Personal  values (1848, 3, 7, 12, 'ELIO', 'VELELA', 'SANZ', 'M');
INSERT INTO Personal  values (1849, 7, 15, 13, 'MAURINO', 'MILPAS', 'HUETO', 'M');
INSERT INTO Personal  values (1850, 10, 1, 8, 'CARLOS TOMAS', 'CANDELERO', 'CAHUICH', 'F');
INSERT INTO Personal  values (1851, 3, 5, 4, 'LEODAN', 'ARCEGA', 'MAYO', 'F');
INSERT INTO Personal  values (1852, 9, 1, 1, 'AMADOR', 'ARROYO', 'TRISTAN', 'F');
INSERT INTO Personal  values (1853, 8, 6, 9, 'BENITO JOSE', 'XOLALTENCO', 'LAZGARE', 'M');
INSERT INTO Personal  values (1854, 10, 4, 2, 'MANASES', 'ROBLES', 'ATTA', 'F');
INSERT INTO Personal  values (1855, 5, 1, 2, 'JOSE REYNALDO', 'MENERA', 'ALAMIRRA', 'M');
INSERT INTO Personal  values (1856, 6, 4, 13, 'ADALBERTO', 'MONCIVAIS', 'ZORRILLA', 'M');
INSERT INTO Personal  values (1857, 10, 9, 3, 'EVERARDO', 'MEDEROS', 'SEDENO', 'M');
INSERT INTO Personal  values (1858, 3, 5, 6, 'JORGE LEOPOLDO', 'BAJONERO', 'CHULIN', 'M');
INSERT INTO Personal  values (1859, 6, 12, 5, 'JUAN GERARDO', 'PATRICIA', 'Y RAMIREZ', 'F');
INSERT INTO Personal  values (1860, 3, 14, 11, 'JESUS MOISES', 'ANDREU', 'GUIZASOLA', 'M');
INSERT INTO Personal  values (1861, 1, 6, 10, 'JORGE DE JESUS', 'CUATETA', 'AMARO', 'F');
INSERT INTO Personal  values (1862, 7, 5, 4, 'DANNY', 'HUIZACHE', 'TERREZ', 'F');
INSERT INTO Personal  values (1863, 3, 4, 5, 'ALFONSO ENRIQUE', 'LEA%OS', 'BOLON', 'M');
INSERT INTO Personal  values (1864, 8, 9, 12, 'EDGAR OMAR', 'VIZCAINO', 'GULUARTE', 'F');
INSERT INTO Personal  values (1865, 3, 2, 11, 'ANIBAL', 'MATEO', 'REQUENA', 'M');
INSERT INTO Personal  values (1866, 4, 12, 1, 'JESUS DIEGO', 'ROMAN', 'MELENA', 'F');
INSERT INTO Personal  values (1867, 3, 8, 6, 'URBINO', 'SARAGOS', 'COETO', 'F');
INSERT INTO Personal  values (1868, 5, 2, 5, 'EDGAR FIDEL', 'PERFECTO', 'CINCO', 'M');
INSERT INTO Personal  values (1869, 10, 3, 10, 'ERIK ALEJANDRO', 'MONTALVO', 'TUXPEO', 'M');
INSERT INTO Personal  values (1870, 5, 13, 1, 'JUAN ERASMO', 'LEVARIO', 'URBIETA', 'M');
INSERT INTO Personal  values (1871, 2, 14, 4, 'EDGAR HOMERO', 'GOROZTIETA', 'LARRIETA', 'F');
INSERT INTO Personal  values (1872, 10, 14, 4, 'LUIS GREGORIO', 'CASTELLANOS', 'QUIROA', 'F');
INSERT INTO Personal  values (1873, 5, 1, 5, 'ORESTE', 'PEDRERA', 'MARINEZ', 'F');
INSERT INTO Personal  values (1874, 1, 5, 8, 'JUAN GABRIE', 'ALCUDIA', 'TIZOC', 'F');
INSERT INTO Personal  values (1875, 6, 1, 7, 'JUAN JORGE', 'CARMELO', 'NIEVES', 'F');
INSERT INTO Personal  values (1876, 7, 4, 11, 'JORGE ADAN', 'VILLAFA%A', 'DE LA CUESTA', 'M');
INSERT INTO Personal  values (1877, 10, 2, 13, 'JOSE OMAR', 'GERVASIO', 'PORTUGAL', 'F');
INSERT INTO Personal  values (1878, 6, 1, 11, 'USIEL', 'CIAU', 'TURRUBIARTES', 'F');
INSERT INTO Personal  values (1879, 3, 6, 12, 'GABRIEL JESUS', 'ZAINOS', 'JARERO', 'M');
INSERT INTO Personal  values (1880, 9, 7, 2, 'JOSE ARTEMIO', 'SALIGAN', 'HERALDEZ', 'M');
INSERT INTO Personal  values (1881, 4, 14, 11, 'PROTACIO', 'PALAZUELOS', 'CARVALLO', 'F');
INSERT INTO Personal  values (1882, 6, 15, 4, 'PEDRO JOAQUIN', 'CAMINO', 'MUOZ', 'M');
INSERT INTO Personal  values (1883, 7, 7, 13, 'CESAR ULISES', 'TAVAREZ', 'ALABAZARES', 'F');
INSERT INTO Personal  values (1884, 4, 11, 8, 'JESUS SAUL', 'ZACAMECAHUA', 'MOHA', 'M');
INSERT INTO Personal  values (1885, 5, 1, 11, 'DANIEL HORACIO', 'ALCORTA', 'CAMPILLO', 'M');
INSERT INTO Personal  values (1886, 2, 10, 3, 'SINUE', 'VARGUEZ', 'CONEJO', 'M');
INSERT INTO Personal  values (1887, 6, 5, 9, 'WALDO', 'ARTEZAN', 'GARIBALDI', 'F');
INSERT INTO Personal  values (1888, 4, 1, 7, 'JOB', 'MAURO', 'ORRANTIA', 'F');
INSERT INTO Personal  values (1889, 1, 10, 1, 'XICOHTENCATL', 'ARRAMBIDE', 'HILARIO', 'F');
INSERT INTO Personal  values (1890, 6, 10, 10, 'JOSE RENE', 'CLETO', 'TUMALAN', 'M');
INSERT INTO Personal  values (1891, 2, 13, 5, 'LEONARDO ALBERTO', 'PANTOJA', 'YAXI', 'M');
INSERT INTO Personal  values (1892, 9, 8, 6, 'JOSE EULALIO', 'CAJIGA', 'FAVILA', 'F');
INSERT INTO Personal  values (1893, 10, 15, 3, 'GUADALUPE JAVIER', 'KOH', 'JUNCO', 'M');
INSERT INTO Personal  values (1894, 7, 2, 11, 'ATALO', 'ESCARE#O', 'SOLORZA', 'F');
INSERT INTO Personal  values (1895, 9, 13, 4, 'RICARDO ADRIAN', 'DEL ROSARIO', 'SUMANO', 'F');
INSERT INTO Personal  values (1896, 1, 8, 12, 'LUIS ISMAEL', 'ORIA', 'LUCATERO', 'F');
INSERT INTO Personal  values (1897, 7, 6, 4, 'SAUL DE JESUS', 'KURY', 'CASTELAR', 'F');
INSERT INTO Personal  values (1898, 2, 13, 3, 'CESAR CUAUHTEMOC', 'ROCHIN', 'MIER', 'M');
INSERT INTO Personal  values (1899, 9, 11, 13, 'ALFONSO ALBERTO', 'SEDEO', 'ARIGUZNAGA', 'F');
INSERT INTO Personal  values (1900, 8, 14, 4, 'VICTOR JOEL', 'MINDER', 'WITZ', 'F');
INSERT INTO Personal  values (1901, 4, 6, 9, 'OSCAR ALONSO', 'DELEON', 'BARQUIN', 'F');
INSERT INTO Personal  values (1902, 9, 8, 4, 'JAIME ALFONSO', 'ARAUJO', 'CARMEN', 'M');
INSERT INTO Personal  values (1903, 6, 15, 10, 'RODOLFO JAVIER', 'MERCED', 'ESCARCEGA', 'F');
INSERT INTO Personal  values (1904, 3, 13, 10, 'AMPELIO', 'O', 'GALLARZO', 'F');
INSERT INTO Personal  values (1905, 6, 11, 9, 'CARLOS ADOLFO', 'J.', 'BOLADO', 'F');
INSERT INTO Personal  values (1906, 10, 9, 9, 'RENE FRANCISCO', 'MONTES DE OCA', 'DEL FIERRO', 'F');
INSERT INTO Personal  values (1907, 3, 10, 5, 'MANUEL MARTIN', 'ROCIO', 'LARIZ', 'F');
INSERT INTO Personal  values (1908, 7, 8, 1, 'FELIX ALBERTO', 'BASTO', 'BOLAϿOS', 'F');
INSERT INTO Personal  values (1909, 5, 14, 1, 'SERGIO ABEL', 'TEMOLTZI', 'HUERFANO', 'M');
INSERT INTO Personal  values (1910, 8, 13, 6, 'JOSE NAZARIO', 'MICHI', 'PORTUGUEZ', 'F');
INSERT INTO Personal  values (1911, 1, 3, 13, 'TLALOC', 'ECHEVESTE', 'SILLERO', 'F');
INSERT INTO Personal  values (1912, 5, 7, 6, 'JUAN JAVIER', 'ZENON', 'REYNOSA', 'F');
INSERT INTO Personal  values (1913, 5, 8, 10, 'CARLOS ESTEBAN', 'ILLESCAS', 'DEFERIA', 'M');
INSERT INTO Personal  values (1914, 1, 8, 11, 'TOMAS', 'CARLO', 'DEL ALTO', 'M');
INSERT INTO Personal  values (1915, 2, 13, 9, 'MARCO VINICIO', 'SALOMON', 'BIBRIESCA', 'M');
INSERT INTO Personal  values (1916, 9, 11, 2, 'JESUS AMADO', 'VALDEMAR', 'ARZAPALO', 'F');
INSERT INTO Personal  values (1917, 10, 11, 5, 'MIGUEL ANDRES', 'ARGUMANIZ', 'DEL CAMPO', 'M');
INSERT INTO Personal  values (1918, 3, 1, 7, 'HECTOR VICENTE', 'CRUZ', 'ENTZIN', 'F');
INSERT INTO Personal  values (1919, 2, 10, 6, 'JOSE BENITO', 'VILLAGRAN', 'PATRICIA', 'F');
INSERT INTO Personal  values (1920, 1, 11, 7, 'FELICITO', 'TREVI#O', 'BURGUENO', 'M');
INSERT INTO Personal  values (1921, 2, 4, 12, 'SAMUEL ANTONIO', 'HERBERTH', 'GARAYZAR', 'M');
INSERT INTO Personal  values (1922, 1, 12, 6, 'RAMON ISRAEL', 'DE HOYOS', 'MILLANES', 'F');
INSERT INTO Personal  values (1923, 2, 2, 4, 'NICASIO', 'GONSALES', 'GALICIA', 'F');
INSERT INTO Personal  values (1924, 4, 10, 3, 'WENCESLAO', 'PARRALES', 'AGUERO', 'M');
INSERT INTO Personal  values (1925, 7, 9, 9, 'JAIME ROBERTO', 'PETRONILO', 'REBOLLO', 'M');
INSERT INTO Personal  values (1926, 1, 8, 6, 'GUILLERMO IGNACIO', 'OTAQUI', 'CERECERO', 'F');
INSERT INTO Personal  values (1927, 9, 8, 10, 'JOAQUIN FRANCISCO', 'MUCIO', 'URRUTIA', 'F');
INSERT INTO Personal  values (1928, 3, 14, 9, 'JAYME', 'CUESTAS', 'SALAIZA', 'M');
INSERT INTO Personal  values (1929, 7, 14, 6, 'JOSE EDMUNDO', 'BACAB', 'GOROSTIETA', 'M');
INSERT INTO Personal  values (1930, 3, 15, 6, 'GUSTAVO ADOLFO', 'ANACLETO', 'SANTIN', 'M');
INSERT INTO Personal  values (1931, 2, 12, 12, 'JESUS ROGELIO', 'JUAN', 'CAMERA', 'M');
INSERT INTO Personal  values (1932, 5, 7, 3, 'JAHAZIEL', 'WITRAGO', 'GARCILAZO', 'F');
INSERT INTO Personal  values (1933, 4, 8, 1, 'ROGELIO OMAR', 'ARACEN', 'SEVERO', 'F');
INSERT INTO Personal  values (1934, 3, 5, 7, 'ARMANDO ALBERTO', 'RECINOS', 'ACU#A', 'F');
INSERT INTO Personal  values (1935, 3, 12, 9, 'ANGEL ISRAEL', 'FAISAL', 'GASTELUM', 'M');
INSERT INTO Personal  values (1936, 6, 11, 12, 'MANUEL ARTURO', 'BASILIO', 'PERTIERRA', 'M');
INSERT INTO Personal  values (1937, 2, 7, 1, 'EDUARDO ANTONIO', 'CORTES', 'BACASEGUA', 'M');
INSERT INTO Personal  values (1938, 7, 5, 5, 'JAVIER OCTAVIO', 'OLIVIER', 'GUEREQUE', 'M');
INSERT INTO Personal  values (1939, 4, 13, 6, 'CARLOS AMADOR', 'BELLIDO', 'CASTAON', 'M');
INSERT INTO Personal  values (1940, 7, 1, 10, 'OMAR ALEXANDER', 'VILLAFUERTE', 'SERRET', 'F');
INSERT INTO Personal  values (1941, 6, 9, 5, 'WALBERTO', 'PIMIENTA', 'ESCARPULLI', 'M');
INSERT INTO Personal  values (1942, 10, 1, 3, 'JULIO JAVIER', 'TORIJA', 'MINDER', 'M');
INSERT INTO Personal  values (1943, 5, 11, 1, 'NAIN', 'CHICATTI', 'FEDERICO', 'M');
INSERT INTO Personal  values (1944, 5, 15, 5, 'CARLOS JORGE', 'SARGENTO', 'EDISON', 'F');
INSERT INTO Personal  values (1945, 8, 3, 2, 'LUIS ESTEBAN', 'FERMAN', 'ESCANDON', 'F');
INSERT INTO Personal  values (1946, 3, 7, 1, 'CARLOS EDMUNDO', 'SEANEZ', 'CATEDRAL', 'M');
INSERT INTO Personal  values (1947, 7, 5, 12, 'RAMON MIGUEL', 'SAIZA', 'JUAN', 'M');
INSERT INTO Personal  values (1948, 3, 3, 4, 'JOSE MARGARITO', 'TEREZA', 'RAIGOZA', 'M');
INSERT INTO Personal  values (1949, 9, 9, 1, 'ARGENIS', 'JIMENO', 'SALTIJERAL', 'M');
INSERT INTO Personal  values (1950, 6, 15, 11, 'JESUS RAMIRO', 'MANTILLA', 'PALMILLAS', 'M');
INSERT INTO Personal  values (1951, 5, 8, 9, 'LIGORIO', 'VIQUE', 'SUCHITE', 'F');
INSERT INTO Personal  values (1952, 9, 9, 1, 'JESUS PAUL', 'BARCELOS', 'SIGALA', 'M');
INSERT INTO Personal  values (1953, 3, 6, 10, 'ERICK OMAR', 'ORDOÿEZ', 'CECILIO', 'M');
INSERT INTO Personal  values (1954, 8, 8, 7, 'ANGEL ARTURO', 'YAMAMOTO', 'BUENRROSTRO', 'F');
INSERT INTO Personal  values (1955, 3, 2, 13, 'PEDRO ISMAEL', 'SANAGUSTIN', 'CRESCENCIO', 'F');
INSERT INTO Personal  values (1956, 10, 6, 13, 'ERICK ROBERTO', 'BENGOA', 'BASHULTO', 'M');
INSERT INTO Personal  values (1957, 5, 8, 13, 'PEDRO DANIEL', 'TRANI', 'TELLEZ GIRON', 'M');
INSERT INTO Personal  values (1958, 5, 4, 5, 'LUIS OCTAVIO', 'BERBER', 'ZAMORA', 'F');
INSERT INTO Personal  values (1959, 4, 7, 3, 'JESUS ABEL', 'CAMERAS', 'CUENCA', 'F');
INSERT INTO Personal  values (1960, 8, 14, 10, 'JUAN PEDRO', 'PEDRO', 'BOCARDO', 'F');
INSERT INTO Personal  values (1961, 6, 4, 9, 'JORGE ELIAS', 'BIZARRO', 'FUNEZ', 'F');
INSERT INTO Personal  values (1962, 9, 8, 8, 'OSCAR RUBEN', 'MARCIANO', 'MARIACA', 'M');
INSERT INTO Personal  values (1963, 6, 8, 4, 'YONATAN', 'LICANO', 'REGINO', 'F');
INSERT INTO Personal  values (1964, 4, 14, 6, 'LUIS MARTIN', 'CHENG', 'INTZIN', 'M');
INSERT INTO Personal  values (1965, 8, 12, 11, 'JUAQUIN', 'TINTOS', 'CHIN', 'F');
INSERT INTO Personal  values (1966, 4, 14, 1, 'MARIO ADRIAN', 'IZAGUIRRE', 'LEYJA', 'F');
INSERT INTO Personal  values (1967, 10, 5, 2, 'JAVIER SANTIAGO', 'GARNELO', 'QUIZAMAN', 'M');
INSERT INTO Personal  values (1968, 1, 12, 13, 'JOSE PONCIANO', 'TRUCIOS', 'MINOR', 'F');
INSERT INTO Personal  values (1969, 4, 13, 9, 'MANUEL FELIPE', 'ABONZA', 'SUASTE', 'M');
INSERT INTO Personal  values (1970, 7, 14, 5, 'EDGAR CESAR', 'OMANA', 'MAZAS', 'F');
INSERT INTO Personal  values (1971, 1, 10, 5, 'JOSE DIEGO', 'TLAPALAMATL', 'MATA', 'M');
INSERT INTO Personal  values (1972, 9, 3, 10, 'JOEL ENRIQUE', 'SOQUI', 'RIBOTA', 'F');
INSERT INTO Personal  values (1973, 2, 6, 13, 'J CONCEPCION', 'ENDOLAY', 'COTE', 'M');
INSERT INTO Personal  values (1974, 7, 12, 1, 'JORGE DAVID', 'SABINA', 'ARCIA', 'F');
INSERT INTO Personal  values (1975, 9, 8, 6, 'HECTOR GUADALUPE', 'MINJARES', 'MESINAS', 'M');
INSERT INTO Personal  values (1976, 9, 10, 2, 'FRANCISCO JAV', 'ANTOLINO', 'MARIELARENA', 'M');
INSERT INTO Personal  values (1977, 3, 5, 7, 'JUAN SIMON', 'DE SANTOS', 'INURRETA', 'F');
INSERT INTO Personal  values (1978, 8, 3, 1, 'HUMBERTO ANTONIO', 'BOLAOS', 'LONA', 'F');
INSERT INTO Personal  values (1979, 2, 2, 4, 'LEON FELIPE', 'CLAVIJO', 'TORQUEMADA', 'F');
INSERT INTO Personal  values (1980, 3, 8, 4, 'JOSE ROSARIO', 'ESTRADA', 'CAMAS', 'F');
INSERT INTO Personal  values (1981, 1, 9, 5, 'RUTILIO', 'RAMAYO', 'MORATO', 'M');
INSERT INTO Personal  values (1982, 3, 2, 1, 'CARLOS SAUL', 'OSCAR', 'DEL MORAL', 'M');
INSERT INTO Personal  values (1983, 9, 2, 11, 'JOSE FELIPE', 'ORO', 'POPO', 'F');
INSERT INTO Personal  values (1984, 4, 14, 7, 'LORETO', 'COSGALLA', 'YAEZ', 'F');
INSERT INTO Personal  values (1985, 3, 10, 9, 'JUAN SANTIAGO', 'BOTELLO', 'CEDENO', 'F');
INSERT INTO Personal  values (1986, 1, 4, 12, 'PEDRO ALFREDO', 'ISAIAS', 'NAREZ', 'M');
INSERT INTO Personal  values (1987, 6, 13, 10, 'RENE FERNANDO', 'JANNUZZI', 'VIA', 'F');
INSERT INTO Personal  values (1988, 7, 3, 6, 'RAUL MARTIN', 'CAMILO', 'ESPERON', 'M');
INSERT INTO Personal  values (1989, 7, 4, 10, 'JESUS A', 'CARRENO', 'ACEBO', 'M');
INSERT INTO Personal  values (1990, 2, 2, 5, 'FERNANDO ALBERTO', 'OCHOA', 'MAXIMIANO', 'F');
INSERT INTO Personal  values (1991, 9, 12, 12, 'LUIS A', 'MILA', 'BOLDO', 'M');
INSERT INTO Personal  values (1992, 9, 15, 11, 'JOSE CELESTINO', 'CHONTAL', 'OGAZ', 'M');
INSERT INTO Personal  values (1993, 1, 8, 10, 'CARITINO', 'AHUACATITLA', 'LARRAAGA', 'F');
INSERT INTO Personal  values (1994, 2, 12, 3, 'JOSE HERNAN', 'CAMIRO', 'CABRIELES', 'M');
INSERT INTO Personal  values (1995, 9, 5, 13, 'HIDELBERTO', 'LORENZANO', 'ARECHAR', 'M');
INSERT INTO Personal  values (1996, 6, 12, 3, 'J ASUNCION', 'YRURZUM', 'GARAVITO', 'F');
INSERT INTO Personal  values (1997, 4, 1, 8, 'J JUAN', 'SALDA%A', 'COCOTLE', 'M');
INSERT INTO Personal  values (1998, 1, 15, 6, 'JAVIER JORGE', 'CUANALO', 'PARRAS', 'M');
INSERT INTO Personal  values (1999, 1, 4, 9, 'URBINO', 'LLARENA', 'FOMPEROSA', 'F');
INSERT INTO Personal  values (2000, 10, 6, 6, 'ALDO', 'STENNER', 'ALDUCIN', 'M');
