DROP TABLE BOLETOS CASCADE CONSTRAINTS;

DROP TABLE CLASIFICACION CASCADE CONSTRAINTS;

DROP TABLE ENTRADAS CASCADE CONSTRAINTS;

DROP TABLE EQUIPO CASCADE CONSTRAINTS;

DROP TABLE ESTADIO CASCADE CONSTRAINTS;

DROP TABLE ESTADISTICAS CASCADE CONSTRAINTS;

DROP TABLE FALTAS CASCADE CONSTRAINTS;

DROP TABLE GOL CASCADE CONSTRAINTS;

DROP TABLE JUGADORES CASCADE CONSTRAINTS;

DROP TABLE PARTIDO CASCADE CONSTRAINTS;

DROP TABLE PASES CASCADE CONSTRAINTS;

DROP TABLE PERSONAL CASCADE CONSTRAINTS;

DROP TABLE PUESTO CASCADE CONSTRAINTS;

DROP TABLE SEDES CASCADE CONSTRAINTS;

DROP TABLE TJUGADO CASCADE CONSTRAINTS;


CREATE TABLE BOLETOS (
    ID_BOLETOS  NUMBER(4) NOT NULL,
    ID_ENTRADA  NUMBER(4) NOT NULL,
    RFC         VARCHAR2(20) NOT NULL,
    METODO_PAGO VARCHAR2(20),
    CANTIDAD    NUMBER(5) NOT NULL
);

CREATE TABLE CLASIFICACION (
    ID_CLASI   NUMBER(4) NOT NULL,
    JORNADA    NUMBER(4) NOT NULL,
    ID_EQUIPO  NUMBER(4) NOT NULL,
    P_JUGADOS  NUMBER(4) NOT NULL,
    P_GANADOS  NUMBER(4),
    P_EMPATE   NUMBER(4) NOT NULL,
    P_PERDIDOS NUMBER(4) NOT NULL,
    PUNTOS     NUMBER(4) NOT NULL
);

CREATE TABLE ENTRADAS (
    ID_ENTRADA NUMBER(4) NOT NULL,
    ID_ESTADIO NUMBER(4) NOT NULL,
    COSTO      NUMBER(5) NOT NULL,
    TIPO       VARCHAR2(20),
    FECHA      DATE
);

CREATE TABLE EQUIPO (
    ID_EQUIPO NUMBER(4) NOT NULL,
    GRUPO     CHAR(1) NOT NULL,
    PAIS      VARCHAR2(20) NOT NULL
);

CREATE TABLE ESTADIO (
    ID_ESTADIO NUMBER(4) NOT NULL,
    ID_SEDE    NUMBER(4) NOT NULL,
    NOMBRE     VARCHAR2(20) NOT NULL,
    CAPACIDAD  NUMBER(5) NOT NULL,
    CALLE      VARCHAR2(20)
);

CREATE TABLE ESTADISTICAS (
    ID_ESTADISTICAS NUMBER(4) NOT NULL,
    ID_JUGADOR      NUMBER(4) NOT NULL,
    PARTIDO         NUMBER(4) NOT NULL
);

CREATE TABLE FALTAS (
    ID_FALTA        NUMBER(4) NOT NULL,
    ID_ESTADISTICAS NUMBER(4) NOT NULL,
    MINUTO          NUMBER(4) NOT NULL,
    TIPO            CHAR(1) NOT NULL
);

CREATE TABLE GOL (
    ID_GOL          NUMBER(4) NOT NULL,
    ID_ESTADISTICAS NUMBER(4) NOT NULL,
    MINUTO          NUMBER(4) NOT NULL,
    TIPO            VARCHAR2(20) NOT NULL
);

CREATE TABLE JUGADORES (
    ID_JUGADOR  NUMBER(4) NOT NULL,
    ID_EQUIPO   NUMBER(4) NOT NULL,
    ID_DTECNICO NUMBER(4),
    NOMBRE      VARCHAR2(20) NOT NULL,
    PATERNO     VARCHAR2(20) NOT NULL,
    EDAD        NUMBER(4) NOT NULL,
    POSICION    VARCHAR2(20) NOT NULL,
    SUELDO      NUMBER(5),
    PAIS_ORIGEN VARCHAR2(20) NOT NULL
);

CREATE TABLE PARTIDO (
    ID_PARTIDO   NUMBER(4) NOT NULL,
    ID_LOCAL     NUMBER(4) NOT NULL,
    ID_VISITANTE NUMBER(4) NOT NULL,
    ID_ESTADIO   NUMBER(4) NOT NULL,
    FECHA        DATE NOT NULL,
    HORA         VARCHAR(20) NOT NULL,
    GOL_L        NUMBER(3),
    GOL_V        NUMBER(3)
);

CREATE TABLE PASES (
    ID_PASE         NUMBER(4) NOT NULL,
    ID_ESTADISTICAS NUMBER(4) NOT NULL,
    TIPO            VARCHAR2(20) NOT NULL
);

CREATE TABLE PERSONAL (
    ID_PERSONAL NUMBER(4) NOT NULL,
    ID_PUESTO   NUMBER(4) NOT NULL,
    ID_JEFE     NUMBER(4) NOT NULL,
    ID_ESTADIO  NUMBER(4) NOT NULL,
    NOMBRE      VARCHAR2(20) NOT NULL,
    APELLIDO1   NUMBER(20) NOT NULL,
    APELLIDO2   VARCHAR2(20) NOT NULL,
    GENERO      VARCHAR2(20)
);

CREATE TABLE PUESTO (
    ID_PUESTO NUMBER(4) NOT NULL,
    NOMBRE    VARCHAR2(20) NOT NULL,
    SUELDO    NUMBER(5) NOT NULL
);

CREATE TABLE SEDES (
    ID_SEDE NUMBER(4)
        CONSTRAINT NNC_SEDES_ID_SEDE NOT NULL,
    AÑO     NUMBER(6) NOT NULL,
    PAIS    VARCHAR2(20) NOT NULL,
    ESTADO  VARCHAR2(20) NOT NULL,
    CIUDAD  VARCHAR2(20) NOT NULL
);

CREATE TABLE TJUGADO (
    ID_TIEMPO       NUMBER(4) NOT NULL,
    JORNADA         NUMBER(4) NOT NULL,
    ID_ESTADISTICAS NUMBER(4) NOT NULL,
    TIEMPOJUGADO    NUMBER(10) NOT NULL
);