insert into SEDES (ID_SEDE, AÑO, PAIS, ESTADO, CIUDAD) values (1, 2018, 'Mexico', 'Guanajuato', 'Kazan');
insert into SEDES (ID_SEDE, AÑO, PAIS, ESTADO, CIUDAD) values (2, 2018, 'Norway', 'Oslo', 'St. Petersburg');
insert into SEDES (ID_SEDE, AÑO, PAIS, ESTADO, CIUDAD) values (3, 2018, 'Mexico', 'Guanajuato', 'Sochi');
insert into SEDES (ID_SEDE, AÑO, PAIS, ESTADO, CIUDAD) values (4, 2018, 'United States', 'Texas', 'St. Petersburg');
insert into SEDES (ID_SEDE, AÑO, PAIS, ESTADO, CIUDAD) values (5, 2018, 'Mexico', 'Chiapas', 'Kazan');
insert into SEDES (ID_SEDE, AÑO, PAIS, ESTADO, CIUDAD) values (6, 2018, 'United States', 'Illinois', 'St. Petersburg');
insert into SEDES (ID_SEDE, AÑO, PAIS, ESTADO, CIUDAD) values (7, 2018, 'Norway', 'Oslo', 'Rostov-On-Don');
insert into SEDES (ID_SEDE, AÑO, PAIS, ESTADO, CIUDAD) values (8, 2018, 'United States', 'Texas', 'Kazan');
insert into SEDES (ID_SEDE, AÑO, PAIS, ESTADO, CIUDAD) values (9, 2018, 'United States', 'Massachusetts', 'Samara');
insert into SEDES (ID_SEDE, AÑO, PAIS, ESTADO, CIUDAD) values (10, 2018, 'United States', 'Ohio', 'Kazan');
