SELECT AVG((GOL_L + GOL_V)) as "Promedio Goles" FROM PARTIDO;

SELECT ID_PARTIDO, AVG((GOL_L+GOL_V))  FROM PARTIDO
GROUP BY ID_PARTIDO
HAVING AVG((GOL_L+GOL_V)) > 2;


SELECT SUM(GOL_L) FROM PARTIDO
WHERE ID_LOCAL = '&EQUIPO' ;
SELECT SUM(GOL_V) FROM PARTIDO
WHERE ID_VISITANTE = '&EQUIPO' ;

SELECT COUNT(*) FROM GOL
WHERE TIPO = 'AUTOGOL';

SELECT COUNT(*) FROM FALTAS
WHERE TIPO = 'A';
SELECT COUNT(*) FROM FALTAS
WHERE TIPO = 'R';