
SELECT J.NOMBRE, J.PATERNO, J.PAIS_ORIGEN
FROM JUGADORES J INNER JOIN EQUIPO E
ON E.ID_EQUIPO = J.ID_EQUIPO
WHERE J.PAIS_ORIGEN = E.PAIS ;

SELECT E.PAIS, COUNT(FAL.ID_FALTA) as "Numero de faltas" FROM EQUIPO E
INNER JOIN JUGADORES J 
ON J.ID_EQUIPO = E.ID_EQUIPO
INNER JOIN ESTADISTICAS ES ON J.ID_JUGADOR = ES.ID_JUGADOR
INNER JOIN FALTAS FAL ON FAL.ID_ESTADISTICAS = ES.ID_ESTADISTICAS
GROUP BY E.PAIS
ORDER BY COUNT(FAL.ID_FALTA) DESC
FETCH FIRST 1 ROWS ONLY;

SELECT E.NOMBRE, COUNT(P.ID_ESTADIO)  FROM ESTADIO E
INNER JOIN PARTIDO P
ON E.ID_ESTADIO = P.ID_ESTADIO
GROUP BY E.NOMBRE
HAVING COUNT(P.ID_ESTADIO) > 3;

SELECT J.NOMBRE, COUNT(G.TIPO) AS GOLES
FROM JUGADORES J INNER JOIN GOL G
ON J.ID_JUGADOR = G.ID_GOL
WHERE G.TIPO = 'GOL' AND ((J.PAIS_ORIGEN = 'Brasil' OR J.ID_JUGADOR = 10) OR (J.PAIS_ORIGEN = 'Alemania' OR J.ID_JUGADOR = 9))
GROUP BY J.NOMBRE
HAVING COUNT(G.TIPO)>1;

SELECT E.NOMBRE, AVG(E.CAPACIDAD) AS PROMEDIO
FROM ESTADIO E INNER JOIN ENTRADAS EN
ON E.ID_ESTADIO = EN.ID_ENTRADA
WHERE EN.FECHA LIKE '1_/12/21'
GROUP BY E.NOMBRE;


SELECT F.MINUTO, COUNT(F.TIPO) AS TOTAL_TARJETAS
FROM FALTAS F INNER JOIN EQUIPO E
ON F.ID_FALTA = E.ID_EQUIPO
INNER JOIN JUGADORES J
ON E.ID_EQUIPO = J.ID_JUGADOR
INNER JOIN ESTADISTICAS ES
ON J.ID_JUGADOR = ES.ID_ESTADISTICAS 
WHERE E.PAIS = 'Egypt' OR E.PAIS = 'Morocco' OR E.PAIS = 'Nigeria' OR E.PAIS = 'Tunisia'
OR E.PAIS = 'Senegal' OR E.PAIS = 'Uruguay' OR E.PAIS = 'Peru' OR E.PAIS = 'Argentina'
OR E.PAIS = 'Brazil' OR E.PAIS = 'Costa Rica' OR E.PAIS = 'Mexico' OR E.PAIS = 'Panama'
OR E.PAIS = 'Colombia'
GROUP BY F.MINUTO;

SELECT F.MINUTO, COUNT(F.TIPO) AS TOTAL_TARJETAS
FROM FALTAS F INNER JOIN EQUIPO E
ON F.ID_FALTA = E.ID_EQUIPO
INNER JOIN JUGADORES J
ON E.ID_EQUIPO = J.ID_JUGADOR
INNER JOIN ESTADISTICAS ES
ON J.ID_JUGADOR = ES.ID_ESTADISTICAS 
WHERE E.PAIS = 'Egypt' OR E.PAIS = 'Morocco' OR E.PAIS = 'Nigeria' OR E.PAIS = 'Tunisia'
OR E.PAIS = 'Senegal' OR E.PAIS = 'Uruguay' OR E.PAIS = 'Peru' OR E.PAIS = 'Argentina'
OR E.PAIS = 'Brazil' OR E.PAIS = 'Costa Rica' OR E.PAIS = 'Mexico' OR E.PAIS = 'Panama' 
OR E.PAIS = 'Colombia'
GROUP BY F.MINUTO;

SELECT F.MINUTO, COUNT(F.TIPO) AS TOTAL_TARJETASROJAS
FROM FALTAS F INNER JOIN EQUIPO E
ON F.ID_FALTA = E.ID_EQUIPO
WHERE ((E.PAIS LIKE 'Argentina' OR E.PAIS LIKE 'Brazil' OR E.PAIS LIKE 'Mexico' OR E.PAIS LIKE 'Germany'
OR E.PAIS LIKE 'Spain' OR E.PAIS LIKE 'France') AND F.TIPO = 'R')
GROUP BY F.MINUTO;

SELECT E.GRUPO AS FINAL
FROM EQUIPO E INNER JOIN CLASIFICACION C
ON E.ID_EQUIPO = C.ID_CLASI
WHERE JORNADA = '5'; 

SELECT E.PAIS AS PARTIDOS_PERDIDOS, C.PUNTOS AS GOLESEN_CONTRA
FROM EQUIPO E INNER JOIN CLASIFICACION C
ON E.ID_EQUIPO = C.ID_EQUIPO
WHERE C.PUNTOS >= '3';

SELECT J.NOMBRE, SUM(P.GOL_L)
FROM JUGADORES J INNER JOIN PARTIDO P
ON J.ID_JUGADOR = P.ID_PARTIDO
WHERE ID_LOCAL = '&EQUIPO'
GROUP BY J.NOMBRE;
SELECT J.NOMBRE, SUM(P.GOL_V)
FROM JUGADORES J INNER JOIN PARTIDO P
ON J.ID_JUGADOR = P.ID_PARTIDO
WHERE ID_VISITANTE = '&EQUIPO' 
GROUP BY J.NOMBRE;