SELECT NOMBRE FROM JUGADORES
WHERE ID_JUGADOR = (SELECT ID_JUGADOR FROM ESTADISTICAS WHERE ID_ESTADISTICAS = (SELECT ID_ESTADISTICAS FROM TJUGADO WHERE TIEMPOJUGADO = 0));

SELECT NOMBRE FROM JUGADORES
WHERE ID_JUGADOR IN (SELECT ID_JUGADOR FROM ESTADISTICAS WHERE ID_ESTADISTICAS IN (SELECT ID_ESTADISTICAS FROM TJUGADO WHERE TIEMPOJUGADO BETWEEN 119 and 120))
FETCH FIRST 5 ROWS ONLY;

SELECT PAIS AS OCTAVOS_FINAL
FROM EQUIPO 
WHERE ID_EQUIPO IN (SELECT ID_CLASI
FROM CLASIFICACION
WHERE JORNADA = '2');

SELECT PAIS 
FROM EQUIPO
WHERE ID_EQUIPO IN (SELECT ID_CLASI
FROM CLASIFICACION
WHERE P_EMPATE >='2');

SELECT PUNTOS
FROM CLASIFICACION
WHERE ID_CLASI IN (SELECT ID_EQUIPO
FROM EQUIPO
WHERE PAIS LIKE 'M%' OR PAIS LIKE'%a');

SELECT TIPO AS GOLES
FROM GOL
WHERE ID_GOL IN (SELECT ID_JUGADOR
FROM JUGADORES
WHERE POSICION = 'Portero');
