CREATE VIEW Portero as
SELECT E.PAIS, COUNT(J.POSICION) as Porteros
FROM EQUIPO E INNER JOIN JUGADORES J
ON E.ID_EQUIPO = J.ID_EQUIPO
WHERE J.POSICION = 'Portero'
GROUP BY E.PAIS;

CREATE VIEW FORMACOMUN_PAGO AS(
SELECT METODO_PAGO, COUNT(METODO_PAGO) AS FORMACOMUN_PAGO
FROM BOLETOS
GROUP BY METODO_PAGO);
SELECT * FROM FORMACOMUN_PAGO;

CREATE VIEW GOLEADORES AS(
SELECT J.NOMBRE, COUNT(G.TIPO) AS GOLES
FROM JUGADORES J INNER JOIN GOL G
ON J.ID_JUGADOR = G.ID_GOL
GROUP BY J.NOMBRE);

CREATE SEQUENCE SQ_ESTADIO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_SEDES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_PUESTO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_BOLETOS
START WITH 5001
INCREMENT BY 1;

CREATE SEQUENCE SQ_PERSONAL
START WITH 2001
INCREMENT BY 1;

CREATE SEQUENCE SQ_ENTRADAS
START WITH 202
INCREMENT BY 1;

CREATE SEQUENCE SQ_PARTIDO
START WITH 66
INCREMENT BY 1;

CREATE SEQUENCE SQ_CLASIFICACION
START WITH 63
INCREMENT BY 1;

CREATE SEQUENCE SQ_EQUIPO
START WITH 66
INCREMENT BY 1;

CREATE SEQUENCE SQ_JUGADORES
START WITH 401
INCREMENT BY 1;

CREATE SEQUENCE SQ_ESTADISTICAS
START WITH 501
INCREMENT BY 1;

CREATE SEQUENCE SQ_FALTAS
START WITH 101
INCREMENT BY 1;

CREATE SEQUENCE SQ_GOL
START WITH 101
INCREMENT BY 1;

CREATE SEQUENCE SQ_PASES
START WITH 101
INCREMENT BY 1;

CREATE SEQUENCE SQ_TJUGADO
START WITH 401
INCREMENT BY 1;

CREATE SEQUENCE SQ_PRUEBA
START WITH 123
INCREMENT BY 2;

